/* mSymGen.h: this header file is automatically generated by executing program
   SymGen with header file(s) as parameter. Please do not make any changes. */
// Command: SymGen doh.txt

#undef  _m9187SYM_H_INC
#ifndef _m9187SYM_H_INC

#define _m9187SYM_H_INC

//from m9187.h

//---------------
#define m_tHDC_INT_all                  0xffff
#define m_tHDC_INT_bits_rsvd_b0_bit4    0x1f
#define m_tHDC_INT_bits_bm              0x20
#define m_tHDC_INT_bits_mpu             0x40
#define m_tHDC_INT_bits_rsvd_b7_b8      0x180
#define m_tHDC_INT_bits_esata           0x200
#define m_tHDC_INT_bits_rsvd_b10_15     0xfc00

//---------------
#define m_tHDC_MPU_status_cpuTO             0x1
#define m_tHDC_MPU_status_rsvd_b1_b15       0xfffe
#define m_tHDC_MPU_reset_all                0xffff
#define m_tHDC_MPU_reset_bits_rsvd_b0_b4    0x1f
#define m_tHDC_MPU_reset_bits_bm            0x60
#define m_tHDC_MPU_reset_bits_rsvd_b7_b15   0xff80
#define m_tHDC_MPU_padR2808                 0xffff
#define m_tHDC_MPU_waitCntr                 0xffff

//---------------
#define m_tTBGcontrol1_TBG_ssc_en       0x1
#define m_tTBGcontrol1_TBG_pu_ssc       0x2
#define m_tTBGcontrol1_TBG_vco_vrng     0xc
#define m_tTBGcontrol1_TBG_kvco         0xf0
#define m_tTBGcontrol1_TBG_vcodiv_sel   0x300
#define m_tTBGcontrol1_rsvd             0x7c00
#define m_tTBGcontrol1_TBG_lock         0x8000

//---------------
#define m_tCLK_PWR_MNGMNT_pwrDownCnt_all                0xffff
#define m_tCLK_PWR_MNGMNT_pwrDownCnt_bits_oscStableCnt  0xf
#define m_tCLK_PWR_MNGMNT_pwrDownCnt_bits_clkSel        0xf0
#define m_tCLK_PWR_MNGMNT_pwrDownCnt_bits_pwrCnt        0xff00
#define m_tCLK_PWR_MNGMNT_clkDiv_cpuClk                 0xf
#define m_tCLK_PWR_MNGMNT_clkDiv_hdcClk                 0xf0
#define m_tCLK_PWR_MNGMNT_clkDiv_rsvd_b8_b15            0xff00
#define m_tCLK_PWR_MNGMNT_clkSel_all                    0xffff
#define m_tCLK_PWR_MNGMNT_clkSel_bits_cpuClk            0x1
#define m_tCLK_PWR_MNGMNT_clkSel_bits_hdcClk            0x2
#define m_tCLK_PWR_MNGMNT_clkSel_bits_rsvd_b2_b13       0x3ffc
#define m_tCLK_PWR_MNGMNT_clkSel_bits_oscClk            0xc000
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_all             0xffff
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_sRomPwrdn  0x1
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_hRomPwrdn  0x2
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_rsvd_b2_b3 0xc
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_rsvd_b4    0x10
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_disBMclk   0x20
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_tcmPwrdnEn 0x40
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_rsvd_b7    0x80
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_tcmNceRdyCnt       0xf00
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_partialPwrdn1      0x1000
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_partialPwrdn2      0x2000
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_fullPwrdn          0x4000
#define m_tCLK_PWR_MNGMNT_pwrMngmtCntrl_bits_oscStabCntTestMode 0x8000
#define m_tCLK_PWR_MNGMNT_pwrCntrl0_all                 0xffff
#define m_tCLK_PWR_MNGMNT_pwrCntrl0_bits_rsvd_b0_b15    0x1
#define m_tCLK_PWR_MNGMNT_pwrCntrl0_bits_nmiIntrStatus  0x2
#define m_tCLK_PWR_MNGMNT_TBGAcontrol_TBGnS             0x1f
#define m_tCLK_PWR_MNGMNT_TBGAcontrol_rstTBGA           0x20
#define m_tCLK_PWR_MNGMNT_TBGAcontrol_disTBGA           0x40
#define m_tCLK_PWR_MNGMNT_TBGAcontrol_TBGnF             0xff80
#define m_tCLK_PWR_MNGMNT_TBGBcontrol_TBGnS             0x1f
#define m_tCLK_PWR_MNGMNT_TBGBcontrol_rstTBGB           0x20
#define m_tCLK_PWR_MNGMNT_TBGBcontrol_disTBGB           0x40
#define m_tCLK_PWR_MNGMNT_TBGBcontrol_TBGnF             0xff80
#define m_tCLK_PWR_MNGMNT_TBGconfig_TBGA_ICHP           0x7
#define m_tCLK_PWR_MNGMNT_TBGconfig_TBGB_ICHP           0x38
#define m_tCLK_PWR_MNGMNT_TBGconfig_TBGAcontrol         0x3c0
#define m_tCLK_PWR_MNGMNT_TBGconfig_TBGBcontrol         0x3c00
#define m_tCLK_PWR_MNGMNT_TBGconfig_rstTBGBdiv          0x4000
#define m_tCLK_PWR_MNGMNT_TBGconfig_rstTBGAdiv          0x8000
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_sscEn            0x1
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_puEn             0x2
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_gain             0xc
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_kvco             0xf0
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_vcoDivSel        0x300
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_rsvd_b10_b14     0x7c00
#define m_tCLK_PWR_MNGMNT_TBGAcontrol1_lock             0x8000
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_sscEn            0x1
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_puEn             0x2
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_gain             0xc
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_kvco             0xf0
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_vcoDivSel        0x300
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_rsvd_b10_b14     0x7c00
#define m_tCLK_PWR_MNGMNT_TBGBcontrol1_lock             0x8000
#define m_tCLK_PWR_MNGMNT_pwrStatus_OSC_stable_cnt      0xf
#define m_tCLK_PWR_MNGMNT_pwrStatus_rsvd_b4_b7          0xf0
#define m_tCLK_PWR_MNGMNT_pwrStatus_PWR_DN_CNT          0xff00
#define m_tCLK_PWR_MNGMNT_clkDiv2_all                   0xffff
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_eccTbgDivSel     0x7
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_rsvd_b3          0x8
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_eccTbgSel        0x10
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_eccClkDis        0x20
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_eccClkSel        0x40
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_rsvd_b7          0x80
#define m_tCLK_PWR_MNGMNT_clkDiv2_bits_rsvd_b8_b15      0xff00
#define m_tCLK_PWR_MNGMNT_clkDiv3_all                   0xffff
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_flaTbgDivSel     0x7
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_rsvd_b3          0x8
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_flaTbgSel        0x10
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_flaClkDis        0x20
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_flaClkSel        0x40
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_rsvd7            0x80
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_flaClkPreSel     0x700
#define m_tCLK_PWR_MNGMNT_clkDiv3_bits_rsvd_b11_b15     0xf800
#define m_tCLK_PWR_MNGMNT_HDCrev                        0xffff

//---------------
#define m_tHBI_QRAM_LBA0_31                 0xffffffff
#define m_tHBI_QRAM_LBA32_47                0xffff
#define m_tHBI_QRAM_nextLink_all            0xff
#define m_tHBI_QRAM_nextLink_bits_NXQ       0x1f
#define m_tHBI_QRAM_nextLink_bits_NXF       0xe0
#define m_tHBI_QRAM_controlbits_all         0xff
#define m_tHBI_QRAM_controlbits_bits_rsvd   0x7
#define m_tHBI_QRAM_controlbits_bits_type   0x8
#define m_tHBI_QRAM_controlbits_bits_op     0x10
#define m_tHBI_QRAM_controlbits_bits_state  0x20
#define m_tHBI_QRAM_controlbits_bits_X      0x40
#define m_tHBI_QRAM_controlbits_bits_A      0x80
#define m_tHBI_QRAM_cmd                     0xff
#define m_tHBI_QRAM_device_head             0xff
#define m_tHBI_QRAM_feature0_15             0xffff
#define m_tHBI_QRAM_bufOffset               0xffffffff

//---------------
#define m_tHBI_TM_STATUS_LOW_all                0xffff
#define m_tHBI_TM_STATUS_LOW_bits_tmFifoParErr  0x1
#define m_tHBI_TM_STATUS_LOW_bits_t10CRCerr     0x2
#define m_tHBI_TM_STATUS_LOW_bits_rdHlbaErr     0x4
#define m_tHBI_TM_STATUS_LOW_bits_hCrc1Err      0x8
#define m_tHBI_TM_STATUS_LOW_bits_qStat         0x30
#define m_tHBI_TM_STATUS_LOW_bits_maxLbaErr     0x40
#define m_tHBI_TM_STATUS_LOW_bits_reTxErr       0x80
#define m_tHBI_TM_STATUS_LOW_bits_crsbParErr    0x100
#define m_tHBI_TM_STATUS_LOW_bits_cxsbParErr    0x200
#define m_tHBI_TM_STATUS_LOW_bits_xmlogsbParErr 0x400
#define m_tHBI_TM_STATUS_LOW_bits_qramParErr    0x800
#define m_tHBI_TM_STATUS_LOW_bits_qTagErr       0x1000
#define m_tHBI_TM_STATUS_LOW_bits_qMixErr       0x2000
#define m_tHBI_TM_STATUS_LOW_bits_qMixNQerr     0x4000
#define m_tHBI_TM_STATUS_LOW_bits_xferPaused    0x8000

//---------------
#define m_tHBI_TM_STATUS_HI_all                     0xffff
#define m_tHBI_TM_STATUS_HI_bits_rpCrsbParErr       0x1
#define m_tHBI_TM_STATUS_HI_bits_rpCmdHistParErr    0x2
#define m_tHBI_TM_STATUS_HI_bits_rpQramParErr       0x4
#define m_tHBI_TM_STATUS_HI_bits_cxsbParErr         0x8
#define m_tHBI_TM_STATUS_HI_bits_rpXmlogsbParErr    0x10
#define m_tHBI_TM_STATUS_HI_bits_rpHfifoParErr      0x20
#define m_tHBI_TM_STATUS_HI_bits_hFIFOunderrun      0x40
#define m_tHBI_TM_STATUS_HI_bits_hFIFOoverrun       0x80
#define m_tHBI_TM_STATUS_HI_bits_rxFpauseDet        0x100
#define m_tHBI_TM_STATUS_HI_bits_bmErrDet           0x200
#define m_tHBI_TM_STATUS_HI_bits_lbgErrDet          0x400
#define m_tHBI_TM_STATUS_HI_bits_lbatErrDet         0x800
#define m_tHBI_TM_STATUS_HI_bits_lbrtErrDet         0x1000
#define m_tHBI_TM_STATUS_HI_bits_newNcqOpDet        0x2000
#define m_tHBI_TM_STATUS_HI_bits_rsvd_b14_b15       0xc000

//---------------
#define m_tHBI_INT_all                  0xffff
#define m_tHBI_INT_bits_hardReset       0x1
#define m_tHBI_INT_bits_softReset       0x2
#define m_tHBI_INT_bits_cmdAborted      0x4
#define m_tHBI_INT_bits_newCmd          0x8
#define m_tHBI_INT_bits_cmdExecErr      0x10
#define m_tHBI_INT_bits_cmdProcessErr   0x20
#define m_tHBI_INT_bits_cmdRcvdErr      0x40
#define m_tHBI_INT_bits_esataErr        0x80
#define m_tHBI_INT_bits_xPortInt        0x100
#define m_tHBI_INT_bits_msgLogDet       0x200
#define m_tHBI_INT_bits_fwXferDone      0x400
#define m_tHBI_INT_bits_xferDone        0x800
#define m_tHBI_INT_bits_nonAceCmd       0x1000
#define m_tHBI_INT_bits_autoWrCmd       0x2000
#define m_tHBI_INT_bits_ncqChangedPriority  0x4000
#define m_tHBI_INT_bits_seqCmdDet       0x8000

//---------------
#define m_tHBI_ACE_CONFIG_1_all                     0xffff
#define m_tHBI_ACE_CONFIG_1_bits_seqWrDmaFuaEn      0x1
#define m_tHBI_ACE_CONFIG_1_bits_seqWrDmaEn         0x2
#define m_tHBI_ACE_CONFIG_1_bits_seqWrStreamDmaEn   0x4
#define m_tHBI_ACE_CONFIG_1_bits_seqWrMultFuaEn     0x8
#define m_tHBI_ACE_CONFIG_1_bits_seqWrMultEn        0x10
#define m_tHBI_ACE_CONFIG_1_bits_seqWrPioEn         0x20
#define m_tHBI_ACE_CONFIG_1_bits_seqWrStreamPioEn   0x40
#define m_tHBI_ACE_CONFIG_1_bits_seqNcqWrEn         0x80
#define m_tHBI_ACE_CONFIG_1_bits_seqNcqRdEn         0x100
#define m_tHBI_ACE_CONFIG_1_bits_seqRdDmaEn         0x200
#define m_tHBI_ACE_CONFIG_1_bits_seqRdStreamDmaEn   0x400
#define m_tHBI_ACE_CONFIG_1_bits_seqRdMultEn        0x800
#define m_tHBI_ACE_CONFIG_1_bits_seqRdPioEn         0x1000
#define m_tHBI_ACE_CONFIG_1_bits_seqRdStreamPioEn   0x2000
#define m_tHBI_ACE_CONFIG_1_bits_rdStreamEn         0x4000
#define m_tHBI_ACE_CONFIG_1_bits_wrStreamEn         0x8000

//---------------
#define m_tHBI_ACE_CONFIG_2_all                     0xffff
#define m_tHBI_ACE_CONFIG_2_bits_wrDmaFuaEn         0x1
#define m_tHBI_ACE_CONFIG_2_bits_wrDmaEn            0x2
#define m_tHBI_ACE_CONFIG_2_bits_wrDmaStreamEn      0x4
#define m_tHBI_ACE_CONFIG_2_bits_wrMultFuaEn        0x8
#define m_tHBI_ACE_CONFIG_2_bits_wrMultEn           0x10
#define m_tHBI_ACE_CONFIG_2_bits_wrPioEn            0x20
#define m_tHBI_ACE_CONFIG_2_bits_wrStreamPioEn      0x40
#define m_tHBI_ACE_CONFIG_2_bits_wrSeqLbaMode       0x80
#define m_tHBI_ACE_CONFIG_2_bits_seqWrLogEn         0x100
#define m_tHBI_ACE_CONFIG_2_bits_seqWrLogStatus     0x200
#define m_tHBI_ACE_CONFIG_2_bits_seqRdLogEn         0x400
#define m_tHBI_ACE_CONFIG_2_bits_seqRdLogStatus     0x800
#define m_tHBI_ACE_CONFIG_2_bits_rsvd_b12_b13       0x3000
#define m_tHBI_ACE_CONFIG_2_bits_wrBuf              0x4000
#define m_tHBI_ACE_CONFIG_2_bits_rsvd_b15           0x8000

//---------------
#define m_tHBI_MSGLOG_CONFIG_all                            0xffff
#define m_tHBI_MSGLOG_CONFIG_bits_aceWrXferStopMsgLogEn     0x1
#define m_tHBI_MSGLOG_CONFIG_bits_aceWrXferStartMsgLogEn    0x2
#define m_tHBI_MSGLOG_CONFIG_bits_seqWrXferStopMsgLogEn     0x4
#define m_tHBI_MSGLOG_CONFIG_bits_seqWrXferStartMsgLogEn    0x8
#define m_tHBI_MSGLOG_CONFIG_bits_seqRdXferStopMsgLogEn     0x10
#define m_tHBI_MSGLOG_CONFIG_bits_seqRdXferStartMsgLogEn    0x20
#define m_tHBI_MSGLOG_CONFIG_bits_wrFuaXferStopMsgLogEn     0x40
#define m_tHBI_MSGLOG_CONFIG_bits_wrFuaXferStartMsgLogEn    0x80
#define m_tHBI_MSGLOG_CONFIG_bits_rsvd_b8_b15               0xff00

//---------------
#define m_tHBI_AUTOSTATUS_CONFIG_all                            0xffff
#define m_tHBI_AUTOSTATUS_CONFIG_bits_ncqSeqRdAutoStatEn        0x1
#define m_tHBI_AUTOSTATUS_CONFIG_bits_ncqSeqWrAutoStatEn        0x2
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqWrStreamDmaAutoStatEn  0x4
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqRdDmaAutoStatEn        0x8
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqRdStreamDmaAutoStatEn  0x10
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqWrDmaAutoStatEn        0x20
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqWrMultAutoStatEn       0x40
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqWrAutoStatEn           0x80
#define m_tHBI_AUTOSTATUS_CONFIG_bits_seqWrStreamAutoStatEn     0x100
#define m_tHBI_AUTOSTATUS_CONFIG_bits_rsvd_b9_b10               0x600
#define m_tHBI_AUTOSTATUS_CONFIG_bits_wbufThresholdChk          0x800
#define m_tHBI_AUTOSTATUS_CONFIG_bits_notifyLbaEn               0x1000
#define m_tHBI_AUTOSTATUS_CONFIG_bits_notifyLbaPause            0x2000
#define m_tHBI_AUTOSTATUS_CONFIG_bits_rsvd_b14_b15              0xc000

//---------------
#define m_tHBI_ACE_OPCODE_0_CONFIG_all          0xffff
#define m_tHBI_ACE_OPCODE_0_CONFIG_bits_rsvd    0xffff

//---------------
#define m_tHBI_ACE_OPCODE_1_CONFIG_all          0xffff
#define m_tHBI_ACE_OPCODE_1_CONFIG_bits_rsvd    0xffff

//---------------
#define m_tHBI_ACE_OPCODE_2_CONFIG_all          0xffff
#define m_tHBI_ACE_OPCODE_2_CONFIG_bits_rsvd    0xffff

//---------------
#define m_tHBI_ACE_OPCODE_3_CONFIG_all          0xffff
#define m_tHBI_ACE_OPCODE_3_CONFIG_bits_rsvd    0xffff

//---------------
#define m_tHBI_ESATA_ERROR_INT_all                      0xffff
#define m_tHBI_ESATA_ERROR_INT_bits_rxCrcErr            0x1
#define m_tHBI_ESATA_ERROR_INT_bits_rxRerrFisDet        0x2
#define m_tHBI_ESATA_ERROR_INT_bits_rxFlowErr           0x4
#define m_tHBI_ESATA_ERROR_INT_bits_rxLengthErr         0x8
#define m_tHBI_ESATA_ERROR_INT_bits_txRerrDet           0x10
#define m_tHBI_ESATA_ERROR_INT_bits_txFlowErr           0x20
#define m_tHBI_ESATA_ERROR_INT_bits_rxRerrDataFisDet    0x40
#define m_tHBI_ESATA_ERROR_INT_bits_tmFifoErr           0x80
#define m_tHBI_ESATA_ERROR_INT_bits_rxDataSyncDet       0x100
#define m_tHBI_ESATA_ERROR_INT_bits_txDataSyncDet       0x200
#define m_tHBI_ESATA_ERROR_INT_bits_txRerrDataFisDet    0x400
#define m_tHBI_ESATA_ERROR_INT_bits_linkCodeErr         0x800
#define m_tHBI_ESATA_ERROR_INT_bits_linkHung            0x1000
#define m_tHBI_ESATA_ERROR_INT_bits_cmdxhTSsaturated    0x2000
#define m_tHBI_ESATA_ERROR_INT_bits_crsbTSsaturated     0x4000
#define m_tHBI_ESATA_ERROR_INT_bits_phyTimeOut          0x8000

//---------------
#define m_tHBI_TM_FLOW_INT_all                      0xffff
#define m_tHBI_TM_FLOW_INT_bits_disAutoRdSeqDet     0x1
#define m_tHBI_TM_FLOW_INT_bits_fuaornewNcqOpDet    0x2
#define m_tHBI_TM_FLOW_INT_bits_RxFisDet            0x4
#define m_tHBI_TM_FLOW_INT_bits_disAutoWrSeqDet     0x8
#define m_tHBI_TM_FLOW_INT_bits_RxBISTfis           0x10
#define m_tHBI_TM_FLOW_INT_bits_RxUserFis           0x20
#define m_tHBI_TM_FLOW_INT_bits_xRDYdet             0x40
#define m_tHBI_TM_FLOW_INT_bits_slumberPMcancel     0x80
#define m_tHBI_TM_FLOW_INT_bits_partialPMcancel     0x100
#define m_tHBI_TM_FLOW_INT_bits_TxFisDone           0x200
#define m_tHBI_TM_FLOW_INT_bits_slumberPM           0x400
#define m_tHBI_TM_FLOW_INT_bits_partialPM           0x800
#define m_tHBI_TM_FLOW_INT_bits_comReset            0x1000
#define m_tHBI_TM_FLOW_INT_bits_comWake             0x2000
#define m_tHBI_TM_FLOW_INT_bits_phyRdy              0x4000
#define m_tHBI_TM_FLOW_INT_bits_phyNotRdy           0x8000

//---------------
#define m_tHBI_TM_RxFIS_ERROR_LOG_all               0xffff
#define m_tHBI_TM_RxFIS_ERROR_LOG_bits_errRxFisType 0xff
#define m_tHBI_TM_RxFIS_ERROR_LOG_bits_rsvd_b8_b15  0xff00

//---------------
#define m_tHBI_TM_TxFIS_ERROR_LOG_all               0xffff
#define m_tHBI_TM_TxFIS_ERROR_LOG_bits_errTxFisType 0xff
#define m_tHBI_TM_TxFIS_ERROR_LOG_bits_rsvd_b8_b15  0xff00

//---------------
#define m_tHBI_TM_RxFIS_LOG_all                 0xffff
#define m_tHBI_TM_RxFIS_LOG_bits_RxFisType      0xff
#define m_tHBI_TM_RxFIS_LOG_bits_rsvd_b8_b11    0xf00
#define m_tHBI_TM_RxFIS_LOG_bits_RxUtype        0x1000
#define m_tHBI_TM_RxFIS_LOG_bits_rsvd_b13       0x2000
#define m_tHBI_TM_RxFIS_LOG_bits_RxForceRErr    0x4000
#define m_tHBI_TM_RxFIS_LOG_bits_RxForceROk     0x8000

//---------------
#define m_tHBI_TM_TxFIS_LOG_all                     0xffff
#define m_tHBI_TM_TxFIS_LOG_bits_TxFisType          0xff
#define m_tHBI_TM_TxFIS_LOG_bits_rsvd_b8_b2         0x1f00
#define m_tHBI_TM_TxFIS_LOG_bits_RxForceSync        0x2000
#define m_tHBI_TM_TxFIS_LOG_bits_rxFisDoneResetEn   0x4000
#define m_tHBI_TM_TxFIS_LOG_bits_txFisDoneResetEn   0x8000

//---------------
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_all               0xffff
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_TxFlowRst    0x1
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_RxFlowRst    0x2
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_linkRst      0x4
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_phyRst       0x8
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_sataBusReq   0x10
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_pwrRdyEn     0x20
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_rsvd_b6      0x40
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_TMsoftRst    0x80
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_rxFlowDis    0x100
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_cmdExeRst    0x200
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_cmdProcRst   0x400
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_ncqPhaseRst  0x800
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_qCntlReset   0x1000
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_rxCntlReset  0x2000
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_lnkSMreset   0x4000
#define m_tHBI_ESATA_FLOW_PWR_RESET_CNTRL_bits_sataBusGranted   0x8000

//---------------
#define m_tHBI_ESATA_CONFIG_all                     0xffff
#define m_tHBI_ESATA_CONFIG_bits_fisRTxEn           0x1
#define m_tHBI_ESATA_CONFIG_bits_rsvd_b1            0x2
#define m_tHBI_ESATA_CONFIG_bits_CDintSel           0x4
#define m_tHBI_ESATA_CONFIG_bits_setHBxferActive    0x8
#define m_tHBI_ESATA_CONFIG_bits_manualFisFlowEn    0x10
#define m_tHBI_ESATA_CONFIG_bits_rsvd_b5_b6         0x60
#define m_tHBI_ESATA_CONFIG_bits_pauseEn            0x80
#define m_tHBI_ESATA_CONFIG_bits_aggregateSDBEn     0x100
#define m_tHBI_ESATA_CONFIG_bits_fDMAactivateDis    0x200
#define m_tHBI_ESATA_CONFIG_bits_rsvd_b10           0x400
#define m_tHBI_ESATA_CONFIG_bits_manualFisXferReq   0x800
#define m_tHBI_ESATA_CONFIG_bits_rabVwaitDis        0x1000
#define m_tHBI_ESATA_CONFIG_bits_ignoreRxdSync      0x2000
#define m_tHBI_ESATA_CONFIG_bits_rsvd_b14_b15       0xc000

//---------------
#define m_tHBI_SATA_MISC_CNTL_all                   0xffff
#define m_tHBI_SATA_MISC_CNTL_bits_reTxCntLimit     0xf
#define m_tHBI_SATA_MISC_CNTL_bits_rsvd_b4_b7       0xf0
#define m_tHBI_SATA_MISC_CNTL_bits_h2dCntRst        0x100
#define m_tHBI_SATA_MISC_CNTL_bits_d2hCntRst        0x200
#define m_tHBI_SATA_MISC_CNTL_bits_phyRdyCntEn      0x400
#define m_tHBI_SATA_MISC_CNTL_bits_sataCntEn        0x800
#define m_tHBI_SATA_MISC_CNTL_bits_rsvd_b12_b15     0xf000

//---------------
#define m_tHBI_HFIFO_CONNECT_THRESHOLD_all                      0xffff
#define m_tHBI_HFIFO_CONNECT_THRESHOLD_bits_hFifoWrThrehResume  0x7f
#define m_tHBI_HFIFO_CONNECT_THRESHOLD_bits_hFifoWrThrehEn      0x80
#define m_tHBI_HFIFO_CONNECT_THRESHOLD_bits_hFifoRdThrehResume  0x7f00
#define m_tHBI_HFIFO_CONNECT_THRESHOLD_bits_hFifoRdThresEn      0x8000

//---------------
#define m_tHBI_TM_MANUAL_FLOW_CNTL_all                  0xffff
#define m_tHBI_TM_MANUAL_FLOW_CNTL_bits_TxManType       0xff
#define m_tHBI_TM_MANUAL_FLOW_CNTL_bits_TxManSel        0x100
#define m_tHBI_TM_MANUAL_FLOW_CNTL_bits_TxFsize         0xe00
#define m_tHBI_TM_MANUAL_FLOW_CNTL_bits_rsvd_b12_b15    0xf000

//---------------
#define m_tHBI_CRSB_PTR_all                 0xffff
#define m_tHBI_CRSB_PTR_bits_readPtr        0x1f
#define m_tHBI_CRSB_PTR_bits_rsvd_b5_b7     0xe0
#define m_tHBI_CRSB_PTR_bits_writePtr       0x1f00
#define m_tHBI_CRSB_PTR_bits_rsvd_b13_b15   0xe000

//---------------
#define m_tHBI_CRSB_DATA_all                0xffff
#define m_tHBI_CRSB_DATA_bits_cmdTag        0x1f
#define m_tHBI_CRSB_DATA_bits_nonQflg       0x20
#define m_tHBI_CRSB_DATA_bits_timeStamp     0xffc0

//---------------
#define m_tHBI_CRSB_CNTL_STAT_all               0xffff
#define m_tHBI_CRSB_CNTL_STAT_bits_count        0x3f
#define m_tHBI_CRSB_CNTL_STAT_bits_fullDet      0x40
#define m_tHBI_CRSB_CNTL_STAT_bits_emptyDet     0x80
#define m_tHBI_CRSB_CNTL_STAT_bits_newIDresume  0x100
#define m_tHBI_CRSB_CNTL_STAT_bits_lastIDresume 0x200
#define m_tHBI_CRSB_CNTL_STAT_bits_paused       0x400
#define m_tHBI_CRSB_CNTL_STAT_bits_pausedReq    0x800
#define m_tHBI_CRSB_CNTL_STAT_bits_parityDis    0x1000
#define m_tHBI_CRSB_CNTL_STAT_bits_rsvd_b13     0x2000
#define m_tHBI_CRSB_CNTL_STAT_bits_rdWrPtrReset 0x4000
#define m_tHBI_CRSB_CNTL_STAT_bits_timeStampReset   0x8000

//---------------
#define m_tHBI_ESATA_MISC_CNTL_STAT_all                 0xffff
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_rtxCnt         0xf
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_rsvd_b4_b7     0xf0
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_h2dCntrReset   0x100
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_d2hCntrReset   0x200
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_phyRdyCntEn    0x400
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_sataCntEn      0x800
#define m_tHBI_ESATA_MISC_CNTL_STAT_bits_rsvd_b12_b15   0xf000

//---------------
#define m_tHBI_CRHS_CNTL_STAT_all                   0xffff
#define m_tHBI_CRHS_CNTL_STAT_bits_wptr             0x1f
#define m_tHBI_CRHS_CNTL_STAT_bits_wrapped          0x20
#define m_tHBI_CRHS_CNTL_STAT_bits_wrPtrRst         0x40
#define m_tHBI_CRHS_CNTL_STAT_bits_timeStampReset   0x80
#define m_tHBI_CRHS_CNTL_STAT_bits_rsvd_b8_b15      0xff00

//---------------
#define m_tHBI_CXSB_PTR_all                 0xffff
#define m_tHBI_CXSB_PTR_bits_readPtr        0x3f
#define m_tHBI_CXSB_PTR_bits_rsvd_b6_b7     0xc0
#define m_tHBI_CXSB_PTR_bits_writePtr       0x3f00
#define m_tHBI_CXSB_PTR_bits_rsvd_b14_b15   0xc000

//---------------
#define m_tHBI_CXSB_CNTL_STAT_all                       0xffff
#define m_tHBI_CXSB_CNTL_STAT_bits_count                0x7f
#define m_tHBI_CXSB_CNTL_STAT_bits_rsvd_b7              0x80
#define m_tHBI_CXSB_CNTL_STAT_bits_reset                0x100
#define m_tHBI_CXSB_CNTL_STAT_bits_pauseEn              0x200
#define m_tHBI_CXSB_CNTL_STAT_bits_fullDet              0x400
#define m_tHBI_CXSB_CNTL_STAT_bits_emptyDet             0x800
#define m_tHBI_CXSB_CNTL_STAT_bits_parityDis            0x1000
#define m_tHBI_CXSB_CNTL_STAT_bits_two16bitWordEntry    0x2000
#define m_tHBI_CXSB_CNTL_STAT_bits_fwWrHold             0x4000
#define m_tHBI_CXSB_CNTL_STAT_bits_hoqHold              0x8000

//---------------
#define m_tHBI_CXSB_FW_REQ0_all                     0xffff
#define m_tHBI_CXSB_FW_REQ0_bits_cmdTag             0x1f
#define m_tHBI_CXSB_FW_REQ0_bits_nonQcmd            0x20
#define m_tHBI_CXSB_FW_REQ0_bits_logXferDoneMsgEn   0x40
#define m_tHBI_CXSB_FW_REQ0_bits_logXferStartMsgEn  0x80
#define m_tHBI_CXSB_FW_REQ0_bits_reqType            0xf00
#define m_tHBI_CXSB_FW_REQ0_bits_bufSegSel          0x7000
#define m_tHBI_CXSB_FW_REQ0_bits_fwReqEocEn         0x8000

//---------------
#define m_tHBI_CXSB_FW_REQ1_all             0xffff
#define m_tHBI_CXSB_FW_REQ1_bits_sectCnt    0xffff

//---------------
#define m_tHBI_CXSB_HOQ_REQ0_all                    0xffff
#define m_tHBI_CXSB_HOQ_REQ0_bits_cmdTag            0x1f
#define m_tHBI_CXSB_HOQ_REQ0_bits_nonQcmd           0x20
#define m_tHBI_CXSB_HOQ_REQ0_bits_logXferDoneMsgEn  0x40
#define m_tHBI_CXSB_HOQ_REQ0_bits_logXferStartMsgEn 0x80
#define m_tHBI_CXSB_HOQ_REQ0_bits_reqType           0xf00
#define m_tHBI_CXSB_HOQ_REQ0_bits_bufSegSel         0x7000
#define m_tHBI_CXSB_HOQ_REQ0_bits_fwReqEocEn        0x8000

//---------------
#define m_tHBI_CXSB_HOQ_REQ1_all                0xffff
#define m_tHBI_CXSB_HOQ_REQ1_bits_sectCnt       0xffff

//---------------
#define m_tHBI_XMLOGSB_PTR_all     0xffff
#define m_tHBI_XMLOGSB_PTR_bits_readPtr     0x3f
#define m_tHBI_XMLOGSB_PTR_bits_rsvd_b6_b7     0xc0
#define m_tHBI_XMLOGSB_PTR_bits_writePtr     0x3f00
#define m_tHBI_XMLOGSB_PTR_bits_rsvd_b14_b15     0xc000

//---------------
#define m_tHBI_XMLOGSB_CNTL_STAT_all     0xffff
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_count     0x3f
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_reset     0x40
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_parityDis     0x80
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_seqRdWoEoc     0x100
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_seqWrWoEoc     0x200
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_hwAutoWr     0x400
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_notifyLba     0x800
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_hwAbortErr     0x1000
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_halfFullDet     0x2000
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_fullDet     0x4000
#define m_tHBI_XMLOGSB_CNTL_STAT_bits_notEmptyDet     0x8000

//---------------
#define m_tHBI_XMLOGSB_DATA_all     0xffff
#define m_tHBI_XMLOGSB_DATA_bits_cmdTag     0x1f
#define m_tHBI_XMLOGSB_DATA_bits_nonQflg     0x20
#define m_tHBI_XMLOGSB_DATA_bits_aceType     0xc0
#define m_tHBI_XMLOGSB_DATA_bits_msgType     0xf00
#define m_tHBI_XMLOGSB_DATA_bits_hwErrMsg     0xf000

//---------------
#define m_tHOST_BUS_INTERFACE_status     0xff
#define m_tHOST_BUS_INTERFACE_error     0xff00
#define m_tHOST_BUS_INTERFACE_altStatus     0xff
#define m_tHOST_BUS_INTERFACE_altError     0xff00
#define m_tHOST_BUS_INTERFACE_sectorNum     0xff
#define m_tHOST_BUS_INTERFACE_cylLow     0xff00
#define m_tHOST_BUS_INTERFACE_cylHigh     0xff
#define m_tHOST_BUS_INTERFACE_devHead     0xff00
#define m_tHOST_BUS_INTERFACE_devCntrl_all     0xffff
#define m_tHOST_BUS_INTERFACE_devCntrl_bits_rsvd_b0     0x1
#define m_tHOST_BUS_INTERFACE_devCntrl_bits_ienN     0x2
#define m_tHOST_BUS_INTERFACE_devCntrl_bits_srst     0x4
#define m_tHOST_BUS_INTERFACE_devCntrl_bits_rsvd_b3_b7     0xf8
#define m_tHOST_BUS_INTERFACE_devCntrl_bits_rsvd_b8_b15     0xff00
#define m_tHOST_BUS_INTERFACE_sectorCnt     0xff
#define m_tHOST_BUS_INTERFACE_PAD0     0xff00
#define m_tHOST_BUS_INTERFACE_ATmode0_all     0xffff
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_lbaRangeEn     0x1
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_maxLbaRangeChkEn     0x2
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_forceDMAxferEn     0x4
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_extLbaMode     0x8
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_hDppEn     0x10
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_hlbaCrc1En     0x20
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_hlbaIncEn     0x40
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_forceCrcErr     0x80
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_hdgT10CrcEn     0x100
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_writeDir     0x200
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_forceMultCmd     0x400
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_rsvd_b11     0x800
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_ncqAutoRelDis     0x1000
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_tcqAutoRelDis     0x2000
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_overrideHWbsy     0x4000
#define m_tHOST_BUS_INTERFACE_ATmode0_bits_MppEn             0x8000
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_all     0xffff
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_stopXfer     0x1
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_clrHbiRst     0x2
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_altHintrq     0x4
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_altHintselq     0x8
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_fwEocIbit     0x10
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_rsvd_b5     0x20
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_waitDmaEn     0x40
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_TmRst     0x80
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_qAbort     0x100
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_execResume     0x200
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_rawLbaSel     0x400
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_rsvd_b11     0x800
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_tfIncEn     0x1000
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_scntDecEn     0x2000
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_rsvd_b14     0x4000
#define m_tHOST_BUS_INTERFACE_ATdevConfgCntrl_bits_updateTF     0x8000
#define m_tHOST_BUS_INTERFACE_autoWrThreshold     0xffff
#define m_tHOST_BUS_INTERFACE_MdataFisSize     0xffff
#define m_tHOST_BUS_INTERFACE_hostBlkSize     0xff
#define m_tHOST_BUS_INTERFACE_RA1C_PAD3     0xff00
#define m_tHOST_BUS_INTERFACE_hostSecPerTrk     0xff
#define m_tHOST_BUS_INTERFACE_hostHdPerCyl     0xff00
#define m_tHOST_BUS_INTERFACE_hostSectorErr     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RA22     0xffff
#define m_tHOST_BUS_INTERFACE_seqSectorNum     0xff
#define m_tHOST_BUS_INTERFACE_seqCylLow     0xff00
#define m_tHOST_BUS_INTERFACE_seqCylHigh     0xff
#define m_tHOST_BUS_INTERFACE_seqDevHead     0xff00
#define m_tHOST_BUS_INTERFACE_PAD_RA28     0xffff
#define m_tHOST_BUS_INTERFACE_initSectorCnt     0xff
#define m_tHOST_BUS_INTERFACE_RA28_PAD7     0xff00
#define m_tHOST_BUS_INTERFACE_initSectorNum     0xff
#define m_tHOST_BUS_INTERFACE_initCylLow     0xff00
#define m_tHOST_BUS_INTERFACE_initCylHigh     0xff
#define m_tHOST_BUS_INTERFACE_initDevHd     0xff00
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_all     0xffff
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_xferStop     0x1
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_xferActive     0x2
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_sRst     0x4
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_laRrdy     0x8
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_txFISstate     0xf0
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_diagNode1     0xf00
#define m_tHOST_BUS_INTERFACE_hostMiscStatus_bits_diagNode2     0xf000
#define m_tHOST_BUS_INTERFACE_aceCntrl_all     0xffff
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_secCntChkEn     0x7
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_rsvd_b3     0x8
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_expandsecCntChk     0x70
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_rsvd_b7     0x80
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_deviceChkEn     0xf00
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_rsvd_b12     0x1000
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_device5ChkEn     0x2000
#define m_tHOST_BUS_INTERFACE_aceCntrl_bits_rsvd_b14_b15     0xc000
#define m_tHOST_BUS_INTERFACE_targetLBALow     0xffff
#define m_tHOST_BUS_INTERFACE_targetLBAMid     0xffff
#define m_tHOST_BUS_INTERFACE_targetLBAHi     0xffff
#define m_tHOST_BUS_INTERFACE_FISsize     0xffff
#define m_tHOST_BUS_INTERFACE_hostBlkXferCnt1_0     0xffff
#define m_tHOST_BUS_INTERFACE_feature1_0_all     0xffff
#define m_tHOST_BUS_INTERFACE_feature1_0_bits_feature0     0xff
#define m_tHOST_BUS_INTERFACE_feature1_0_bits_feature1     0xff00
#define m_tHOST_BUS_INTERFACE_lba1_0_all     0xffff
#define m_tHOST_BUS_INTERFACE_lba1_0_bits_lba0     0xff
#define m_tHOST_BUS_INTERFACE_lba1_0_bits_lba1     0xff00
#define m_tHOST_BUS_INTERFACE_lba3_2_all     0xffff
#define m_tHOST_BUS_INTERFACE_lba3_2_bits_lba2     0xff
#define m_tHOST_BUS_INTERFACE_lba3_2_bits_lba3     0xff00
#define m_tHOST_BUS_INTERFACE_lba5_4_all     0xffff
#define m_tHOST_BUS_INTERFACE_lba5_4_bits_lba4     0xff
#define m_tHOST_BUS_INTERFACE_lba5_4_bits_lba5     0xff00
#define m_tHOST_BUS_INTERFACE_sectorCnt0_1     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqLba01     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqLba23     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqLba45     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RA4E     0xffff
#define m_tHOST_BUS_INTERFACE_initialLba1_0     0xffff
#define m_tHOST_BUS_INTERFACE_initialLba3_2     0xffff
#define m_tHOST_BUS_INTERFACE_initialLba5_4     0xffff
#define m_tHOST_BUS_INTERFACE_initialSectCnt1_0_all     0xffff
#define m_tHOST_BUS_INTERFACE_initialSectCnt1_0_bits_initialSectCnt0     0xff
#define m_tHOST_BUS_INTERFACE_initialSectCnt1_0_bits_initialSectCnt1     0xff00
#define m_tHOST_BUS_INTERFACE_cmnd     0xff
#define m_tHOST_BUS_INTERFACE_PAD_REGA03     0xff00
#define m_tHOST_BUS_INTERFACE_streamIdConf_all     0xffff
#define m_tHOST_BUS_INTERFACE_streamIdConf_bits_rdStreamId     0xf
#define m_tHOST_BUS_INTERFACE_streamIdConf_bits_wrStreamId     0xf0
#define m_tHOST_BUS_INTERFACE_streamIdConf_bits_rsvd_b8_b15     0xff00
#define m_tHOST_BUS_INTERFACE_wrSeqLba01     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqLba23     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqLba45     0xffff
#define m_tHOST_BUS_INTERFACE_wbufThreshold     0xffff
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_all     0xffff
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_bits_manualSegSel     0x7
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_bits_rdSeqSegSel     0x38
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_bits_wrSeqSegSel     0x1c0
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_bits_wrDmaSegSel     0xe00
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_bits_wrPioSegSel     0x7000
#define m_tHOST_BUS_INTERFACE_hostBufferSegSel_bits_rsvd_b15     0x8000
#define m_tHOST_BUS_INTERFACE_PAD_RA6E     0xffff
#define m_tHOST_BUS_INTERFACE_tmFIFOthreshold_all     0xffff
#define m_tHOST_BUS_INTERFACE_tmFIFOthreshold_bits_tmFifoThresh     0xf
#define m_tHOST_BUS_INTERFACE_tmFIFOthreshold_bits_rsvd_b4_b7     0xf0
#define m_tHOST_BUS_INTERFACE_tmFIFOthreshold_bits_tmFifoWordCnt     0xff00
#define m_tHOST_BUS_INTERFACE_tmFifoReadWrite_all     0xffff
#define m_tHOST_BUS_INTERFACE_tmFifoReadWrite_bits_HFifoWrtPtr     0x7f
#define m_tHOST_BUS_INTERFACE_tmFifoReadWrite_bits_rsvd_b7     0x80
#define m_tHOST_BUS_INTERFACE_tmFifoReadWrite_bits_HFifoRdPtr     0x7f00
#define m_tHOST_BUS_INTERFACE_tmFifoReadWrite_bits_rsvd_b15     0x8000
#define m_tHOST_BUS_INTERFACE_qExePartialStatLo     0xffff
#define m_tHOST_BUS_INTERFACE_qExePartialStatHi     0xffff
#define m_tHOST_BUS_INTERFACE_qExePendStatLo     0xffff
#define m_tHOST_BUS_INTERFACE_qExePendStatHi     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RA7C     0xffff
#define m_tHOST_BUS_INTERFACE_overrideCntl_all     0xffff
#define m_tHOST_BUS_INTERFACE_overrideCntl_bits_rsvd     0xffff
#define m_tHOST_BUS_INTERFACE_qCmdBsyStatLo     0xffff
#define m_tHOST_BUS_INTERFACE_qCmdBsyStatHi     0xffff
#define m_tHOST_BUS_INTERFACE_lbaErrorLo     0xffff
#define m_tHOST_BUS_INTERFACE_lbaErrorMid     0xffff
#define m_tHOST_BUS_INTERFACE_lbaErrorHi     0xffff
#define m_tHOST_BUS_INTERFACE_qActiveLo     0xffff
#define m_tHOST_BUS_INTERFACE_qActiveHi     0xffff
#define m_tHOST_BUS_INTERFACE_qTagIDlow     0xffff
#define m_tHOST_BUS_INTERFACE_qTagIDhi     0xffff
#define m_tHOST_BUS_INTERFACE_bistPat     0xffff
#define m_tHOST_BUS_INTERFACE_bistWord1Lo     0xffff
#define m_tHOST_BUS_INTERFACE_bistWord1Hi     0xffff
#define m_tHOST_BUS_INTERFACE_bistWord2Lo     0xffff
#define m_tHOST_BUS_INTERFACE_bistWord2Hi     0xffff
#define m_tHOST_BUS_INTERFACE_disparityCnt     0xffff
#define m_tHOST_BUS_INTERFACE_codeErrCnt     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS0L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS0H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS1L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS1H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS2L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS2H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS3L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS3H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS4L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS4H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS5L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS5H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS6L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS6H     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS7L     0xffff
#define m_tHOST_BUS_INTERFACE_uRegFIS7H     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RAE2     0xffff
#define m_tHOST_BUS_INTERFACE_wrMaxLBA1_0     0xffff
#define m_tHOST_BUS_INTERFACE_wrMaxLBA3_2     0xffff
#define m_tHOST_BUS_INTERFACE_wrMaxLBA5_4     0xffff
#define m_tHOST_BUS_INTERFACE_rdMaxLBA1_0     0xffff
#define m_tHOST_BUS_INTERFACE_rdMaxLBA3_2     0xffff
#define m_tHOST_BUS_INTERFACE_rdMaxLBA5_4     0xffff
#define m_tHOST_BUS_INTERFACE_maxLBA1_0     0xffff
#define m_tHOST_BUS_INTERFACE_maxLBA3_2     0xffff
#define m_tHOST_BUS_INTERFACE_maxLBA5_4     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RAFE     0xffff
#define m_tHOST_BUS_INTERFACE_cxsbCurr0     0xffff
#define m_tHOST_BUS_INTERFACE_cxsbCurr1     0xffff
#define m_tHOST_BUS_INTERFACE_d2hReTxCnt     0xffff
#define m_tHOST_BUS_INTERFACE_d2hRerrCnt     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDataCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDataCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_d2hPioCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_d2hPioCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDmaActCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDmaActCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_d2hNDCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_d2hNDCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDDWCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDDWCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_d2hNDDWCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_d2hNDDWCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RB2C     0xffff
#define m_tHOST_BUS_INTERFACE_d2hDmaSetupCnt     0xffff
#define m_tHOST_BUS_INTERFACE_h2dNDDisparityCnt     0xffff
#define m_tHOST_BUS_INTERFACE_h2dNDCrcErrCnt     0xffff
#define m_tHOST_BUS_INTERFACE_h2dDataCrcErrCnt     0xffff
#define m_tHOST_BUS_INTERFACE_h2dDataDisparityCnt     0xffff
#define m_tHOST_BUS_INTERFACE_h2dDataCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_h2dDataCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_h2dNonDataFisCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_h2dNonDataFisCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_h2dDataDwordCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_h2dDDWCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_h2dNDDWCntLo     0xffff
#define m_tHOST_BUS_INTERFACE_h2dNDDWCntHi     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RB4E     0xffff
#define m_tHOST_BUS_INTERFACE_timestampClkCntrLo     0xffff
#define m_tHOST_BUS_INTERFACE_timestampClkCntrHi     0xffff
#define m_tHOST_BUS_INTERFACE_tmPhase     0xffff
#define m_tHOST_BUS_INTERFACE_hDWxfrCnt     0xffff
#define m_tHOST_BUS_INTERFACE_mistPat1Low     0xffff
#define m_tHOST_BUS_INTERFACE_mistPat1Hi     0xffff
#define m_tHOST_BUS_INTERFACE_mistPat2Low     0xffff
#define m_tHOST_BUS_INTERFACE_mistPat2Hi     0xffff
#define m_tHOST_BUS_INTERFACE_mistPat3Low     0xffff
#define m_tHOST_BUS_INTERFACE_mistPat3Hi     0xffff
#define m_tHOST_BUS_INTERFACE_mistCntl     0xffff
#define m_tHOST_BUS_INTERFACE_mistCmdAndType     0xffff
#define m_tHOST_BUS_INTERFACE_waitDmaBlkCnt     0xffff
#define m_tHOST_BUS_INTERFACE_mistCmdHistTimestamp     0xffff
#define m_tHOST_BUS_INTERFACE_hFifoDataLo     0xffff
#define m_tHOST_BUS_INTERFACE_hFifoDataHi     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RB78     0xffff
#define m_tHOST_BUS_INTERFACE_hFifoTestPtr     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqStartLba01     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqStartLba23     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqStartLba45     0xffff
#define m_tHOST_BUS_INTERFACE_latchedStatErr     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqCmdCntrLow     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqCmdCntr1Hi     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqSectCntrLow     0xffff
#define m_tHOST_BUS_INTERFACE_rdSeqSectCntr1Hi     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqStartLba01     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqStartLba23     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqStartLba45     0xffff
#define m_tHOST_BUS_INTERFACE_PAD_RB96     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqCmdCntrLow     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqCmdCntr1Hi     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqSectCntrLow     0xffff
#define m_tHOST_BUS_INTERFACE_wrSeqSectCntr1Hi     0xffff
#define m_tHOST_BUS_INTERFACE_seqMultThreadConfig1     0xffff
#define m_tHOST_BUS_INTERFACE_seqMultThreadConfig2     0xffff
#define m_tHOST_BUS_INTERFACE_bistCntl     0xffff
#define m_tHOST_BUS_INTERFACE_bistStatus     0xffff
#define m_tHOST_BUS_INTERFACE_errInjectCntrMatchLo     0xffff
#define m_tHOST_BUS_INTERFACE_errInjectCntrMatchHi     0xffff
#define m_tHOST_BUS_INTERFACE_errInjectCntl     0xffff
#define m_tHOST_BUS_INTERFACE_bufBlkXferCnt     0xffff

//---------------
#define m_tPHYLINK_STATUS_LOW_all     0xffff
#define m_tPHYLINK_STATUS_LOW_bits_det     0xf
#define m_tPHYLINK_STATUS_LOW_bits_Spd     0xf0
#define m_tPHYLINK_STATUS_LOW_bits_ipm     0xf00
#define m_tPHYLINK_STATUS_LOW_bits_rsvd_b12_b15     0xf000

//---------------
#define m_tPHYLINK_ERROR_LOW_all     0xffff
#define m_tPHYLINK_ERROR_LOW_bits_rsvd_b0     0x1
#define m_tPHYLINK_ERROR_LOW_bits_recComErr     0x2
#define m_tPHYLINK_ERROR_LOW_bits_rsvd_b2_b15     0xfffc

//---------------
#define m_tPHYLINK_ERROR_HIGH_all     0xffff
#define m_tPHYLINK_ERROR_HIGH_bits_phyRdyChg     0x1
#define m_tPHYLINK_ERROR_HIGH_bits_phyInErr     0x2
#define m_tPHYLINK_ERROR_HIGH_bits_comWake     0x4
#define m_tPHYLINK_ERROR_HIGH_bits_decodeErr     0x8
#define m_tPHYLINK_ERROR_HIGH_bits_disparityErr     0x10
#define m_tPHYLINK_ERROR_HIGH_bits_crcErr     0x20
#define m_tPHYLINK_ERROR_HIGH_bits_rErr     0x40
#define m_tPHYLINK_ERROR_HIGH_bits_linkSeqErr     0x80
#define m_tPHYLINK_ERROR_HIGH_bits_tpStateErr     0x100
#define m_tPHYLINK_ERROR_HIGH_bits_unrecFIS     0x200
#define m_tPHYLINK_ERROR_HIGH_bits_xFlag     0x400
#define m_tPHYLINK_ERROR_HIGH_bits_rsvd11     0x800
#define m_tPHYLINK_ERROR_HIGH_bits_hostDiscErr     0x1000
#define m_tPHYLINK_ERROR_HIGH_bits_rsvd15_13     0xe000

//---------------
#define m_tPHYLINK_CONTROL_LOW_all     0xffff
#define m_tPHYLINK_CONTROL_LOW_bits_phyStateMode     0xf
#define m_tPHYLINK_CONTROL_LOW_bits_speedConfig     0xf0
#define m_tPHYLINK_CONTROL_LOW_bits_pmConfig     0xf00
#define m_tPHYLINK_CONTROL_LOW_bits_pmStateSel     0xf000

//---------------
#define m_tPHYLINK_LTMODE_LOW_all     0xffff
#define m_tPHYLINK_LTMODE_LOW_bits_txComWakeHold     0x1
#define m_tPHYLINK_LTMODE_LOW_bits_rsvd_b1_b3     0xe
#define m_tPHYLINK_LTMODE_LOW_bits_fTxCrcErr     0x10
#define m_tPHYLINK_LTMODE_LOW_bits_syncrecovDis     0x20
#define m_tPHYLINK_LTMODE_LOW_bits_rsvd_b6     0x40
#define m_tPHYLINK_LTMODE_LOW_bits_nearEndLupBack     0x80
#define m_tPHYLINK_LTMODE_LOW_bits_linkStateMode     0x100
#define m_tPHYLINK_LTMODE_LOW_bits_rErrEn     0x200
#define m_tPHYLINK_LTMODE_LOW_bits_crcMode     0x400
#define m_tPHYLINK_LTMODE_LOW_bits_crcCheckDis     0x800
#define m_tPHYLINK_LTMODE_LOW_bits_rxScrbDis     0x1000
#define m_tPHYLINK_LTMODE_LOW_bits_txScrbDis     0x2000
#define m_tPHYLINK_LTMODE_LOW_bits_contEn     0x4000
#define m_tPHYLINK_LTMODE_LOW_bits_phyBypass     0x8000

//---------------
#define m_tPHYLINK_LTMODE_HIGH_all     0xffff
#define m_tPHYLINK_LTMODE_HIGH_bits_oobSyncLock     0x1
#define m_tPHYLINK_LTMODE_HIGH_bits_txDMAsel     0x2
#define m_tPHYLINK_LTMODE_HIGH_bits_linkTimer     0x4
#define m_tPHYLINK_LTMODE_HIGH_bits_ignoreSrst     0x8
#define m_tPHYLINK_LTMODE_HIGH_bits_rxDMATsel     0x10
#define m_tPHYLINK_LTMODE_HIGH_bits_d10OOBen     0x20
#define m_tPHYLINK_LTMODE_HIGH_bits_deviceTo     0x40
#define m_tPHYLINK_LTMODE_HIGH_bits_pmAckExtEn     0x80
#define m_tPHYLINK_LTMODE_HIGH_bits_txPrimDis     0x100
#define m_tPHYLINK_LTMODE_HIGH_bits_rsvd_b9_b10     0x600
#define m_tPHYLINK_LTMODE_HIGH_bits_speedAdjEn     0x800
#define m_tPHYLINK_LTMODE_HIGH_bits_allignThreshold     0x3000
#define m_tPHYLINK_LTMODE_HIGH_bits_commaDetEn     0x4000
#define m_tPHYLINK_LTMODE_HIGH_bits_synClockMode     0x8000

//---------------
#define m_tPHYLINK_INTERFACE_sataStatHigh     0xffff
#define m_tPHYLINK_INTERFACE_sataCntlHi     0xffff
#define m_tPHYLINK_INTERFACE_phyLinkTestCntl     0xffff
#define m_tPHYLINK_INTERFACE_oobConf1Lo     0xffff
#define m_tPHYLINK_INTERFACE_oobConf1Hi     0xffff
#define m_tPHYLINK_INTERFACE_oobConf2Lo     0xffff
#define m_tPHYLINK_INTERFACE_oobConf2Hi     0xffff
#define m_tPHYLINK_INTERFACE_oobConf3Lo     0xffff
#define m_tPHYLINK_INTERFACE_oobConf3Hi     0xffff
#define m_tPHYLINK_INTERFACE_oobConf4     0xffff
#define m_tPHYLINK_INTERFACE_PAD_R582E     0xffff
#define m_tPHYLINK_INTERFACE_phyConfLo     0xffff
#define m_tPHYLINK_INTERFACE_phyConfHi     0xffff
#define m_tPHYLINK_INTERFACE_idleCnt     0xffff
#define m_tPHYLINK_INTERFACE_powerCntl     0xffff
#define m_tPHYLINK_INTERFACE_alignThr     0xffff
#define m_tPHYLINK_INTERFACE_phySMconfig0     0xffff
#define m_tPHYLINK_INTERFACE_testCntlLo_all     0xffff
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_BISTtestCFG     0xff
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_BISTmode     0x100
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_BISTen     0x200
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_BISTresult     0x400
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_rsvd_b11     0x800
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_rsvd_b12     0x1000
#define m_tPHYLINK_INTERFACE_testCntlLo_bits_rsvd_b13_b15     0xe000
#define m_tPHYLINK_INTERFACE_newtestCntlHi     0xffff
#define m_tPHYLINK_INTERFACE_newPhyMode1Lo     0xffff
#define m_tPHYLINK_INTERFACE_newPhyMode1Hi     0xffff
#define m_tPHYLINK_INTERFACE_newPhyMode4Lo     0xffff
#define m_tPHYLINK_INTERFACE_newPhyMode4Hi     0xffff
#define m_tPHYLINK_INTERFACE_newPhyTestCntl     0xffff
#define m_tPHYLINK_INTERFACE_PhyRevision     0xffff
#define m_tPHYLINK_INTERFACE_PllRate     0xffff
#define m_tPHYLINK_INTERFACE_PhySpeedCntl     0xffff
#define m_tPHYLINK_INTERFACE_PllBWAdjust     0xffff
#define m_tPHYLINK_INTERFACE_CalCntl     0xffff
#define m_tPHYLINK_INTERFACE_ImpCal     0xffff
#define m_tPHYLINK_INTERFACE_ImpCntl     0xffff
#define m_tPHYLINK_INTERFACE_DccKvcoCntl     0xffff
#define m_tPHYLINK_INTERFACE_PreDeEmphasisEn     0xffff
#define m_tPHYLINK_INTERFACE_AmpEmphCntl     0xffff
#define m_tPHYLINK_INTERFACE_SlewRateSelect     0xffff
#define m_tPHYLINK_INTERFACE_SSCCntl     0xffff
#define m_tPHYLINK_INTERFACE_SqDetThrSetting     0xffff
#define m_tPHYLINK_INTERFACE_CdrInitCoeffVal     0xffff
#define m_tPHYLINK_INTERFACE_DtlSqPhLoopCntl     0xffff
#define m_tPHYLINK_INTERFACE_FFeRCCntl     0xffff
#define m_tPHYLINK_INTERFACE_DFeCoeffResCntl     0xffff
#define m_tPHYLINK_INTERFACE_DFeF0F1CoeffCntl     0xffff
#define m_tPHYLINK_INTERFACE_DFeF2F5CoeffCntl     0xffff
#define m_tPHYLINK_INTERFACE_DFeMisc0     0xffff
#define m_tPHYLINK_INTERFACE_DFeCoeffCntl     0xffff
#define m_tPHYLINK_INTERFACE_DFeTimer     0xffff
#define m_tPHYLINK_INTERFACE_EOMCktCntl     0xffff
#define m_tPHYLINK_INTERFACE_EOMSet1Cntl0     0xffff
#define m_tPHYLINK_INTERFACE_EOMSet1Cntl1     0xffff
#define m_tPHYLINK_INTERFACE_EOMSet2Cntl0     0xffff
#define m_tPHYLINK_INTERFACE_EOMSet2Cntl1     0xffff
#define m_tPHYLINK_INTERFACE_G1Setting0     0xffff
#define m_tPHYLINK_INTERFACE_G1Setting1     0xffff
#define m_tPHYLINK_INTERFACE_G2Setting0     0xffff
#define m_tPHYLINK_INTERFACE_G2Setting1     0xffff
#define m_tPHYLINK_INTERFACE_G3Setting0     0xffff
#define m_tPHYLINK_INTERFACE_G3Setting1     0xffff
#define m_tPHYLINK_INTERFACE_ConfigReg0     0xffff
#define m_tPHYLINK_INTERFACE_PllRegOutputCntl0     0xffff
#define m_tPHYLINK_INTERFACE_PowerCntlReg     0xffff
#define m_tPHYLINK_INTERFACE_ResetCntl     0xffff
#define m_tPHYLINK_INTERFACE_PhyTestCntl0     0xffff
#define m_tPHYLINK_INTERFACE_PhyTestCntl1     0xffff
#define m_tPHYLINK_INTERFACE_DigitalLoopbackEn     0xffff
#define m_tPHYLINK_INTERFACE_Misc1     0xffff
#define m_tPHYLINK_INTERFACE_SyncPat     0xffff
#define m_tPHYLINK_INTERFACE_SyncMask     0xffff

//---------------
#define m_tBM_CNTRL_REG1_all     0xffff
#define m_tBM_CNTRL_REG1_bits_hostBurstLenSel     0x7
#define m_tBM_CNTRL_REG1_bits_diskBurstLenSel     0x38
#define m_tBM_CNTRL_REG1_bits_rsvd_b6     0x40
#define m_tBM_CNTRL_REG1_bits_bmDPDPen     0x80
#define m_tBM_CNTRL_REG1_bits_rsvd_b8     0x100
#define m_tBM_CNTRL_REG1_bits_intModeSel     0x200
#define m_tBM_CNTRL_REG1_bits_rsvd11_10     0xc00
#define m_tBM_CNTRL_REG1_bits_DRAMstart     0x1000
#define m_tBM_CNTRL_REG1_bits_DRAMPwrDownStart     0x2000
#define m_tBM_CNTRL_REG1_bits_rsvd_b15_14     0xc000

//---------------
#define m_tBM_CNTRL_REG0_all     0xffff
#define m_tBM_CNTRL_REG0_bits_rsvd_b0     0x1
#define m_tBM_CNTRL_REG0_bits_diskByteCntrRst     0x2
#define m_tBM_CNTRL_REG0_bits_rsvd_b2_3     0xc
#define m_tBM_CNTRL_REG0_bits_sdramWpEn     0x10
#define m_tBM_CNTRL_REG0_bits_rsvd_b5     0x20
#define m_tBM_CNTRL_REG0_bits_diskMatchStopEn     0x40
#define m_tBM_CNTRL_REG0_bits_hostMatchStopEn     0x80
#define m_tBM_CNTRL_REG0_bits_ssdParityEn     0x100
#define m_tBM_CNTRL_REG0_bits_ssdWpEn     0x200
#define m_tBM_CNTRL_REG0_bits_rsvd_b10_11     0xc00
#define m_tBM_CNTRL_REG0_bits_extBurstLenSel     0x7000
#define m_tBM_CNTRL_REG0_bits_rsvd_b15     0x8000

//---------------
#define m_tBM_RR_CNTRL0_all     0xffff
#define m_tBM_RR_CNTRL0_bits_slotClientSel0     0x7
#define m_tBM_RR_CNTRL0_bits_slotClientSel1     0x38
#define m_tBM_RR_CNTRL0_bits_slotClientSel2     0x1c0
#define m_tBM_RR_CNTRL0_bits_slotClientSel3     0xe00
#define m_tBM_RR_CNTRL0_bits_slotClientSel4     0x7000
#define m_tBM_RR_CNTRL0_bits_rsvd_b15     0x8000

//---------------
#define m_tBM_RR_CNTRL1_all     0xffff
#define m_tBM_RR_CNTRL1_bits_slotClientSel5     0x7
#define m_tBM_RR_CNTRL1_bits_slotClientSel6     0x38
#define m_tBM_RR_CNTRL1_bits_slotClientSel7     0x1c0
#define m_tBM_RR_CNTRL1_bits_slotClientSel8     0xe00
#define m_tBM_RR_CNTRL1_bits_rsvd_b9_15     0xf000

//---------------
#define m_tBM_SHARED_2_SLOT_CNTRL_all     0xffff
#define m_tBM_SHARED_2_SLOT_CNTRL_bits_s2_priority0     0x7
#define m_tBM_SHARED_2_SLOT_CNTRL_bits_s2_priority1     0x38
#define m_tBM_SHARED_2_SLOT_CNTRL_bits_s2_priority2     0x1c0
#define m_tBM_SHARED_2_SLOT_CNTRL_bits_s2_priority3     0xe00
#define m_tBM_SHARED_2_SLOT_CNTRL_bits_s2_priority4     0x7000
#define m_tBM_SHARED_2_SLOT_CNTRL_bits_rsvd_b15     0x8000

//---------------
#define m_tBM_SHARED_1_SLOT_CNTRL_all     0xffff
#define m_tBM_SHARED_1_SLOT_CNTRL_bits_s1_priority0     0x7
#define m_tBM_SHARED_1_SLOT_CNTRL_bits_s1_priority1     0x38
#define m_tBM_SHARED_1_SLOT_CNTRL_bits_s1_priority2     0x1c0
#define m_tBM_SHARED_1_SLOT_CNTRL_bits_s1_priority3     0xe00
#define m_tBM_SHARED_1_SLOT_CNTRL_bits_s1_priority4     0x7000
#define m_tBM_SHARED_1_SLOT_CNTRL_bits_rsvd_b15     0x8000

//---------------
#define m_tBM_SHARED_3_SLOT_CNTRL_all     0xffff
#define m_tBM_SHARED_3_SLOT_CNTRL_bits_s3_priority0     0x7
#define m_tBM_SHARED_3_SLOT_CNTRL_bits_s3_priority1     0x38
#define m_tBM_SHARED_3_SLOT_CNTRL_bits_s3_priority2     0x1c0
#define m_tBM_SHARED_3_SLOT_CNTRL_bits_s3_priority3     0xe00
#define m_tBM_SHARED_3_SLOT_CNTRL_bits_s3_priority4     0x7000
#define m_tBM_SHARED_3_SLOT_CNTRL_bits_rsvd_b15     0x8000

//---------------
#define m_tBM_RR_SLOT_MASK_all     0xffff
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask0     0x1
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask1     0x2
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask2     0x4
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask3     0x8
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask4     0x10
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask5     0x20
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask6     0x40
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask7     0x80
#define m_tBM_RR_SLOT_MASK_bits_rrSlotMask8     0x100
#define m_tBM_RR_SLOT_MASK_bits_rsvd_b9_15     0xfe00

//---------------
#define m_tBM_STAT0_all     0xffff
#define m_tBM_STAT0_bits_rsvd_b0_2     0x7
#define m_tBM_STAT0_bits_extToWp     0x8
#define m_tBM_STAT0_bits_hostToWp     0x10
#define m_tBM_STAT0_bits_diskToWp     0x20
#define m_tBM_STAT0_bits_rsvd_b6     0x40
#define m_tBM_STAT0_bits_mpuToWp     0x80
#define m_tBM_STAT0_bits_hostSsdParErr     0x100
#define m_tBM_STAT0_bits_diskSsdParErr     0x200
#define m_tBM_STAT0_bits_rsvd_b11_10     0xc00
#define m_tBM_STAT0_bits_diskSegEmpty     0x1000
#define m_tBM_STAT0_bits_diskSegFull     0x2000
#define m_tBM_STAT0_bits_curHSegEmpty     0x4000
#define m_tBM_STAT0_bits_curHSegFull     0x8000

//---------------
#define m_tBM_STAT1_all     0xffff
#define m_tBM_STAT1_bits_HLL0matched     0x1
#define m_tBM_STAT1_bits_HLL1matched     0x2
#define m_tBM_STAT1_bits_HLL2matched     0x4
#define m_tBM_STAT1_bits_HLL3matched     0x8
#define m_tBM_STAT1_bits_HLL4matched     0x10
#define m_tBM_STAT1_bits_HLL5matched     0x20
#define m_tBM_STAT1_bits_HLL6matched     0x40
#define m_tBM_STAT1_bits_HLL7matched     0x80
#define m_tBM_STAT1_bits_DLL0matched     0x100
#define m_tBM_STAT1_bits_DLL1matched     0x200
#define m_tBM_STAT1_bits_DLL2matched     0x400
#define m_tBM_STAT1_bits_DLL3matched     0x800
#define m_tBM_STAT1_bits_rsvd_b12     0x1000
#define m_tBM_STAT1_bits_ELLmatchStop     0x2000
#define m_tBM_STAT1_bits_HLLmatchStop     0x4000
#define m_tBM_STAT1_bits_DLLmatchStop     0x8000

//---------------
#define m_tBM_STAT2_all     0xffff
#define m_tBM_STAT2_bits_ddrLock_L0     0x1
#define m_tBM_STAT2_bits_ddrLock_L1     0x2
#define m_tBM_STAT2_bits_ddrInitDone     0x4
#define m_tBM_STAT2_bits_rsvd_b3     0x8
#define m_tBM_STAT2_bits_ddrTimeout     0x10
#define m_tBM_STAT2_bits_rsvd_b5_14     0x7fe0
#define m_tBM_STAT2_bits_dramRdy     0x8000

//---------------
#define m_tBM_STAT3_all     0xffff
#define m_tBM_STAT3_bits_es0LLmatch     0x1
#define m_tBM_STAT3_bits_es1LLmatch     0x2
#define m_tBM_STAT3_bits_es2LLmatch     0x4
#define m_tBM_STAT3_bits_es3LLmatch     0x8
#define m_tBM_STAT3_bits_rsvd_b4_7     0xf0
#define m_tBM_STAT3_bits_extSsdParErr     0x100
#define m_tBM_STAT3_bits_rsvd_b9_11     0xe00
#define m_tBM_STAT3_bits_extSegEmpty     0x1000
#define m_tBM_STAT3_bits_extSegFull     0x2000
#define m_tBM_STAT3_bits_rsvd_b14_15     0xc000

//---------------
#define m_tBM_DRAM_CNTRL_REG1_all     0xffff
#define m_tBM_DRAM_CNTRL_REG1_bits_tWrSel     0x7
#define m_tBM_DRAM_CNTRL_REG1_bits_refreshModeSel     0x8
#define m_tBM_DRAM_CNTRL_REG1_bits_tRPSel     0x70
#define m_tBM_DRAM_CNTRL_REG1_bits_multiRowDis     0x80
#define m_tBM_DRAM_CNTRL_REG1_bits_memSize     0x700
#define m_tBM_DRAM_CNTRL_REG1_bits_ckeCtl     0x1800
#define m_tBM_DRAM_CNTRL_REG1_bits_dblDdrEn     0x2000
#define m_tBM_DRAM_CNTRL_REG1_bits_rsvd_b14     0x4000
#define m_tBM_DRAM_CNTRL_REG1_bits_ddr3En     0x8000

//---------------
#define m_tBM_DRAM_CNTRL_REG0_all     0xffff
#define m_tBM_DRAM_CNTRL_REG0_bits_tRFC     0x3f
#define m_tBM_DRAM_CNTRL_REG0_bits_otfZQ     0x40
#define m_tBM_DRAM_CNTRL_REG0_bits_tWtrSel     0x180
#define m_tBM_DRAM_CNTRL_REG0_bits_rsvd_b9_10     0x600
#define m_tBM_DRAM_CNTRL_REG0_bits_tRasSel     0x7800
#define m_tBM_DRAM_CNTRL_REG0_bits_dramReset     0x8000

//---------------
#define m_tBM_REF_PRD_all     0xffff
#define m_tBM_REF_PRD_bits_value     0x1fff
#define m_tBM_REF_PRD_bits_rsvd_b13_15     0xe000

//---------------
#define m_tBM_DRAM_EXT_MODE2_all     0xffff
#define m_tBM_DRAM_EXT_MODE2_bits_rsvd_b0_2     0x7
#define m_tBM_DRAM_EXT_MODE2_bits_cwl     0x38
#define m_tBM_DRAM_EXT_MODE2_bits_sdramExt2mode     0x7fc0
#define m_tBM_DRAM_EXT_MODE2_bits_emr2WrEn     0x8000

//---------------
#define m_tBM_DRAM_EXT_MODE_all     0xffff
#define m_tBM_DRAM_EXT_MODE_bits_sdramExtMode3Regs     0x7fff
#define m_tBM_DRAM_EXT_MODE_bits_emr3WrEn     0x8000

//---------------
#define m_tBM_DRAM_MODE_CNTL_all     0xffff
#define m_tBM_DRAM_MODE_CNTL_bits_burstLen     0x7
#define m_tBM_DRAM_MODE_CNTL_bits_burstType     0x8
#define m_tBM_DRAM_MODE_CNTL_bits_cas_ltncy     0x70
#define m_tBM_DRAM_MODE_CNTL_bits_rsvd_b7     0x80
#define m_tBM_DRAM_MODE_CNTL_bits_dramDllRst     0x100
#define m_tBM_DRAM_MODE_CNTL_bits_ddrWrRecovery     0xe00
#define m_tBM_DRAM_MODE_CNTL_bits_dllCtrlPpd     0x1000
#define m_tBM_DRAM_MODE_CNTL_bits_rsvd_b13_14     0x6000
#define m_tBM_DRAM_MODE_CNTL_bits_ModeWrEn     0x8000

//---------------
#define m_tBM_DRAM_MODE_CNTL_all     0xffff
#define m_tBM_DRAM_MODE_CNTL_bits_mode     0x7fff
#define m_tBM_DRAM_MODE_CNTL_bits_wrEn     0x8000

//---------------
#define m_tBM_DRAM_EXT_MODE1_all     0xffff
#define m_tBM_DRAM_EXT_MODE1_bits_dllEn     0x1
#define m_tBM_DRAM_EXT_MODE1_bits_dicSel     0x2
#define m_tBM_DRAM_EXT_MODE1_bits_odtB0     0x4
#define m_tBM_DRAM_EXT_MODE1_bits_addLtncy     0x38
#define m_tBM_DRAM_EXT_MODE1_bits_odtB1     0x40
#define m_tBM_DRAM_EXT_MODE1_bits_ocdModeEn     0x380
#define m_tBM_DRAM_EXT_MODE1_bits_dqsEn     0x400
#define m_tBM_DRAM_EXT_MODE1_bits_rdqsEn     0x800
#define m_tBM_DRAM_EXT_MODE1_bits_rsvd_b12_14     0x7000
#define m_tBM_DRAM_EXT_MODE1_bits_emr1WrEn     0x8000

//---------------
#define m_tBM_DRAM_TM_CMD_all     0xffff
#define m_tBM_DRAM_TM_CMD_bits_ddrCmd     0xf
#define m_tBM_DRAM_TM_CMD_bits_rsvd     0x7ff0
#define m_tBM_DRAM_TM_CMD_bits_updateEn     0x8000

//---------------
#define m_tBM_DRAM_TM_ADDR_all     0xffff
#define m_tBM_DRAM_TM_ADDR_bits_sdramAddr     0x1fff
#define m_tBM_DRAM_TM_ADDR_bits_bs     0x6000
#define m_tBM_DRAM_TM_ADDR_bits_reserved     0x8000

//---------------
#define m_tHOST_LNK_LST_PTR_all     0xffff
#define m_tHOST_LNK_LST_PTR_bits_pointer     0xffff

//---------------
#define m_tDISK_LNK_LST_PTR_all     0xffff
#define m_tDISK_LNK_LST_PTR_bits_pointer     0xffff

//---------------
#define m_tEXTD_LNK_LST_PTR_all     0xffff
#define m_tEXTD_LNK_LST_PTR_bits_pointer     0xffff

//---------------
#define m_tHOST_EXP_LNK_LST_PTR_all     0xffff
#define m_tHOST_EXP_LNK_LST_PTR_bits_expHLLptr     0xffff

//---------------
#define m_tDISK_EXP_LNK_LST_PTR_all     0xffff
#define m_tDISK_EXP_LNK_LST_PTR_bits_expHLLptr     0xffff

//---------------
#define m_tEXTD_EXP_LNK_LST_PTR_all     0xffff
#define m_tEXTD_EXP_LNK_LST_PTR_bits_expHLLptr     0xffff

//---------------
#define m_tHOST_LNK_LST_STOP_PTR_all     0xffff
#define m_tHOST_LNK_LST_STOP_PTR_bits_hllStopPtr     0xffff

//---------------
#define m_tDISK_LNK_LST_STOP_PTR_all     0xffff
#define m_tDISK_LNK_LST_STOP_PTR_bits_dllStopPtr     0xffff

//---------------
#define m_tEXTD_LNK_LST_STOP_PTR_all     0xffff
#define m_tEXTD_LNK_LST_STOP_PTR_bits_dllStopPtr     0xffff

//---------------
#define m_tHOST_SECTOR_SIZE_all     0xffff
#define m_tHOST_SECTOR_SIZE_bits_size     0x1fff
#define m_tHOST_SECTOR_SIZE_bits_rsvd     0xe000

//---------------
#define m_tDISK_SECTOR_SIZE_all     0xffff
#define m_tDISK_SECTOR_SIZE_bits_size     0x1fff
#define m_tDISK_SECTOR_SIZE_bits_rsvd     0xe000

//---------------
#define m_tEXTD_SECTOR_SIZE_all     0xffff
#define m_tEXTD_SECTOR_SIZE_bits_size     0x1fff
#define m_tEXTD_SECTOR_SIZE_bits_rsvd     0xe000

//---------------
#define m_tDISK_SEG_SEL_all     0xffff
#define m_tDISK_SEG_SEL_bits_dskSegsel     0x3
#define m_tDISK_SEG_SEL_bits_rsvd_b2_14     0x7ffc
#define m_tDISK_SEG_SEL_bits_dskSegSelEn     0x8000

//---------------
#define m_tSUB_SEG_SIZE_SEL_all     0xffff
#define m_tSUB_SEG_SIZE_SEL_bits_ssdSize     0xf
#define m_tSUB_SEG_SIZE_SEL_bits_rsvd1     0xfff0

//---------------
#define m_tDISK_LOG_SECTOR_CNT_SEL_all     0xffff
#define m_tDISK_LOG_SECTOR_CNT_SEL_bits_dskLSSC     0xf
#define m_tDISK_LOG_SECTOR_CNT_SEL_bits_rsvd4     0x10
#define m_tDISK_LOG_SECTOR_CNT_SEL_bits_hstSSCtoSSC1     0x20
#define m_tDISK_LOG_SECTOR_CNT_SEL_bits_rsvd6     0xffc0

//---------------
#define m_tHOST_CUR_SEG_SEL_all     0xffff
#define m_tHOST_CUR_SEG_SEL_bits_curhSegSel     0x7
#define m_tHOST_CUR_SEG_SEL_bits_rsvd3     0xfff8

//---------------
#define m_tDISK_STREAM_CTRL_all     0xffff
#define m_tDISK_STREAM_CTRL_bits_diskHostSel     0xf
#define m_tDISK_STREAM_CTRL_bits_rsvd_b4_6     0x70
#define m_tDISK_STREAM_CTRL_bits_host2disk     0x80
#define m_tDISK_STREAM_CTRL_bits_diskExtdSel     0x700
#define m_tDISK_STREAM_CTRL_bits_rsvd_b11_14     0x7800
#define m_tDISK_STREAM_CTRL_bits_extd2disk     0x8000

//---------------
#define m_tHOST_STREAM_CTRL_all     0xffff
#define m_tHOST_STREAM_CTRL_bits_hostDiskSel     0x7
#define m_tHOST_STREAM_CTRL_bits_rsvd_b3_6     0x78
#define m_tHOST_STREAM_CTRL_bits_disk2host     0x80
#define m_tHOST_STREAM_CTRL_bits_hostExtdSel     0x700
#define m_tHOST_STREAM_CTRL_bits_rsvd_b11_14     0x7800
#define m_tHOST_STREAM_CTRL_bits_extd2host     0x8000

//---------------
#define m_tEXTD_STREAM_CTRL_all     0xffff
#define m_tEXTD_STREAM_CTRL_bits_extdHostSel     0xf
#define m_tEXTD_STREAM_CTRL_bits_rsvd_b4_6     0x70
#define m_tEXTD_STREAM_CTRL_bits_host2extd     0x80
#define m_tEXTD_STREAM_CTRL_bits_extdDiskSel     0x700
#define m_tEXTD_STREAM_CTRL_bits_rsvd_b11_14     0x7800
#define m_tEXTD_STREAM_CTRL_bits_disk2extd     0x8000

//---------------
#define m_tSSD_CTRL_all     0xffff
#define m_tSSD_CTRL_bits_descSize     0x1
#define m_tSSD_CTRL_bits_extdDescCntEn     0x2
#define m_tSSD_CTRL_bits_hostDescCntEn     0x4
#define m_tSSD_CTRL_bits_diskDescCntEn     0x8
#define m_tSSD_CTRL_bits_rsvd_b7     0x10
#define m_tSSD_CTRL_bits_extdDescCntMode     0x20
#define m_tSSD_CTRL_bits_hostDescCntMode     0x40
#define m_tSSD_CTRL_bits_diskDescCntMode     0x80
#define m_tSSD_CTRL_bits_rsvd_b11_b15     0x1f00

//---------------
#define m_tBUFF_MNGR_PAD2E24     0xffff
#define m_tBUFF_MNGR_sectorSizeRatio     0xffff
#define m_tBUFF_MNGR_hostSegAdjSel     0xffff
#define m_tBUFF_MNGR_diskSegAdjSel     0xffff
#define m_tBUFF_MNGR_curExtdSegSectorCnt     0xffff
#define m_tBUFF_MNGR_curExtdSegFreeSpace     0xffff
#define m_tBUFF_MNGR_extdSegSectCntAdj     0xffff
#define m_tBUFF_MNGR_extdSegAdjSel     0xffff
#define m_tBUFF_MNGR_extdSegSel     0xffff
#define m_tBUFF_MNGR_PADF64     0xffff
#define m_tBUFF_MNGR_wpStartAddrL     0xffff
#define m_tBUFF_MNGR_wpStartAddrH     0xffff
#define m_tBUFF_MNGR_wpEndAddrL     0xffff
#define m_tBUFF_MNGR_wpEndAddrH     0xffff
#define m_tBUFF_MNGR_ssdTableStartL     0xffff
#define m_tBUFF_MNGR_ssdTableStartH     0xffff
#define m_tBUFF_MNGR_ssdTableEndL     0xffff
#define m_tBUFF_MNGR_ssdTableEndH     0xffff
#define m_tBUFF_MNGR_currSSD_31_0     0xffffffff
#define m_tBUFF_MNGR_currSSD_63_32     0xffffffff
#define m_tBUFF_MNGR_currSSD_95_64     0xffffffff

//---------------
#define m_tDDO_BLOCK_ddoControl_all     0xffff
#define m_tDDO_BLOCK_ddoControl_bits_w64Ddo     0x1
#define m_tDDO_BLOCK_ddoControl_bits_w128Ddo     0x2
#define m_tDDO_BLOCK_ddoControl_bits_reserved2     0x7ffc
#define m_tDDO_BLOCK_ddoControl_bits_ddoRdy     0x8000
#define m_tDDO_BLOCK_ddoConfig_all     0xffff
#define m_tDDO_BLOCK_ddoConfig_bits_ddoClkDiv     0x3
#define m_tDDO_BLOCK_ddoConfig_bits_reserved12     0xfffc
#define m_tDDO_BLOCK_ddoBits15_0     0xffff
#define m_tDDO_BLOCK_ddoBits31_16     0xffff
#define m_tDDO_BLOCK_ddoBits47_32     0xffff
#define m_tDDO_BLOCK_ddoBits63_48     0xffff
#define m_tDDO_BLOCK_ddoBits79_64     0xffff
#define m_tDDO_BLOCK_ddoBits95_80     0xffff
#define m_tDDO_BLOCK_ddoBits111_96     0xffff
#define m_tDDO_BLOCK_ddoBits127_112     0xffff

//---------------
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_all     0xffff
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_intnlErrInjctEn     0x1
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_extnlErrInjctEn     0x2
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_svo_dt_mode     0xc
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_TAerrInjctEn     0x10
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_sbdErrInjctEn     0x20
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_sbdSMFErrInjctEn     0x40
#define m_tERR_INJECTION_BLOCK_ErrInjectionCtrl_bits_rsvd15_7     0xff80
#define m_tERR_INJECTION_BLOCK_ErrInjectionStatus_all     0xffff
#define m_tERR_INJECTION_BLOCK_ErrInjectionStatus_bits_intnlLocMatch     0x1
#define m_tERR_INJECTION_BLOCK_ErrInjectionStatus_bits_extnlTriggerDet     0x2
#define m_tERR_INJECTION_BLOCK_ErrInjectionStatus_bits_rsvd     0xfffc
#define m_tERR_INJECTION_BLOCK_intrnlErrInjctLSNStart     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlErrInjctLSNEnd     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlErrInjctSSNStart     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlErrInjctSSNEnd     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlDataErrInjctLoc0     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlDataErrInjctLoc1     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlServoErrInjctLoc0     0xffff
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat0_all     0xffff
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat0_bits_intnlErrInjctPat0     0xff
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat0_bits_rsvd     0x3f00
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat0_bits_errType0     0xc000
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat1_all     0xffff
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat1_bits_intnlErrInjctPat1     0xff
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat1_bits_rsvd     0x3f00
#define m_tERR_INJECTION_BLOCK_dataErrInjectionPat1_bits_errType1     0xc000
#define m_tERR_INJECTION_BLOCK_servoErrInjectionPat0_all     0xffff
#define m_tERR_INJECTION_BLOCK_servoErrInjectionPat0_bits_intnlErrInjctSvoPat0     0xff
#define m_tERR_INJECTION_BLOCK_servoErrInjectionPat0_bits_rsvd     0x3f00
#define m_tERR_INJECTION_BLOCK_servoErrInjectionPat0_bits_errTypeSrv0     0xc000
#define m_tERR_INJECTION_BLOCK_intrnlErrInjctDataLen     0xffff
#define m_tERR_INJECTION_BLOCK_intrnlErrInjctServoLen     0xffff
//  #if (mSMART == mENABLE)    
//  #endif

//---------------
#define m_tSEQ_INT_all     0xffff
#define m_tSEQ_INT_bits_trkDone     0x1
#define m_tSEQ_INT_bits_trkErr     0x2
#define m_tSEQ_INT_bits_rsvd0     0xc
#define m_tSEQ_INT_bits_opDone     0x10
#define m_tSEQ_INT_bits_auxFiFoUndrFlow     0x20
#define m_tSEQ_INT_bits_desOverFlow     0x40
#define m_tSEQ_INT_bits_trkOverFlow     0x80
#define m_tSEQ_INT_bits_auDecDoneOvFlow     0x100
#define m_tSEQ_INT_bits_auEncDoneOvFlow     0x200
#define m_tSEQ_INT_bits_rsvd1     0xfc00

//---------------
#define m_tNV_SEQ_seqConfig1_all     0xffff
#define m_tNV_SEQ_seqConfig1_bits_rsvd     0x1f
#define m_tNV_SEQ_seqConfig1_bits_paRatio     0x60
#define m_tNV_SEQ_seqConfig1_bits_trkStatusHold     0x80
#define m_tNV_SEQ_seqConfig1_bits_maxActTrk     0x7f00
#define m_tNV_SEQ_seqConfig1_bits_trkOrder     0x8000
#define m_tNV_SEQ_seqConfig2_all     0xffff
#define m_tNV_SEQ_seqConfig2_bits_sramAutoPd     0x1
#define m_tNV_SEQ_seqConfig2_bits_noLastAu     0x2
#define m_tNV_SEQ_seqConfig2_bits_auxDataMode     0x4
#define m_tNV_SEQ_seqConfig2_bits_auxDataXferMode     0x8
#define m_tNV_SEQ_seqConfig2_bits_auxFifoCPUPri     0x10
#define m_tNV_SEQ_seqConfig2_bits_desFifoCPUPri     0x20
#define m_tNV_SEQ_seqConfig2_bits_sramPdTh     0x1c0
#define m_tNV_SEQ_seqConfig2_bits_enAbortIntr     0x200
#define m_tNV_SEQ_seqConfig2_bits_sramPdExit     0x1c00
#define m_tNV_SEQ_seqConfig2_bits_rsvd     0x6000
#define m_tNV_SEQ_seqConfig2_bits_sqClkDis     0x8000
#define m_tNV_SEQ_rsvd0     0xffff
#define m_tNV_SEQ_seqConfig3_all     0xffff
#define m_tNV_SEQ_seqConfig3_bits_trkSramRtc     0x3
#define m_tNV_SEQ_seqConfig3_bits_trkSramWtc     0xc
#define m_tNV_SEQ_seqConfig3_bits_sramPd     0x10
#define m_tNV_SEQ_seqConfig3_bits_aFifoSramRtc     0x60
#define m_tNV_SEQ_seqConfig3_bits_aFifoSramwtc     0x180
#define m_tNV_SEQ_seqConfig3_bits_aFifoSramPd     0x200
#define m_tNV_SEQ_seqConfig3_bits_dFifoSramRtc     0xc00
#define m_tNV_SEQ_seqConfig3_bits_dFifoSramWtc     0x3000
#define m_tNV_SEQ_seqConfig3_bits_dFifoSramPd     0x4000
#define m_tNV_SEQ_seqConfig3_bits_rsvd     0x8000
#define m_tNV_SEQ_seqControl1_all     0xffff
#define m_tNV_SEQ_seqControl1_bits_seqBusy     0x1
#define m_tNV_SEQ_seqControl1_bits_rsvd0     0xe
#define m_tNV_SEQ_seqControl1_bits_decAutoWr     0x30
#define m_tNV_SEQ_seqControl1_bits_encAutoWr     0xc0
#define m_tNV_SEQ_seqControl1_bits_dlcAdjFail     0x100
#define m_tNV_SEQ_seqControl1_bits_rsvd1     0xe00
#define m_tNV_SEQ_seqControl1_bits_seqEnable     0x1000
#define m_tNV_SEQ_seqControl1_bits_seqAbtMode     0x2000
#define m_tNV_SEQ_seqControl1_bits_rsvd2     0x4000
#define m_tNV_SEQ_seqControl1_bits_seqReset     0x8000
#define m_tNV_SEQ_rsvd2     0xffff
#define m_tNV_SEQ_trkStatusId_all     0xffff
#define m_tNV_SEQ_trkStatusId_bits_trkId     0x7f
#define m_tNV_SEQ_trkStatusId_bits_rsvd     0xff80
#define m_tNV_SEQ_trkPointer_all     0xffff
#define m_tNV_SEQ_trkPointer_bits_desStatusPtr     0x1f
#define m_tNV_SEQ_trkPointer_bits_rsvd0     0xe0
#define m_tNV_SEQ_trkPointer_bits_desRdyBusyPtr     0x300
#define m_tNV_SEQ_trkPointer_bits_rsvd1     0xc00
#define m_tNV_SEQ_trkPointer_bits_desDonePtr     0x7000
#define m_tNV_SEQ_trkPointer_bits_rsvd2     0x8000
#define m_tNV_SEQ_trkOverallStatusL_all     0xffff
#define m_tNV_SEQ_trkOverallStatusL_bits_trkPos     0x1
#define m_tNV_SEQ_trkOverallStatusL_bits_trkLos     0x2
#define m_tNV_SEQ_trkOverallStatusL_bits_desProc     0x1fc
#define m_tNV_SEQ_trkOverallStatusL_bits_desTot     0xfe00
#define m_tNV_SEQ_trkOverallStatusH_all     0xffff
#define m_tNV_SEQ_trkOverallStatusH_bits_errAuNum     0x1f
#define m_tNV_SEQ_trkOverallStatusH_bits_errAuDesId     0xfe0
#define m_tNV_SEQ_trkOverallStatusH_bits_errAuType     0x1000
#define m_tNV_SEQ_trkOverallStatusH_bits_rsvd     0xe000
#define m_tNV_SEQ_trkDesDone_all     0xffffffff
#define m_tNV_SEQ_trkDesDone_words_trkDesDoneL     0xffff
#define m_tNV_SEQ_trkDesDone_words_trkDesDoneH     0xffff
#define m_tNV_SEQ_trkDesRdyBusy_all     0xffffffff
#define m_tNV_SEQ_trkDesRdyBusy_words_trkDesRdyBusyL     0xffff
#define m_tNV_SEQ_trkDesRdyBusy_words_trkDesRdyBusyH     0xffff
#define m_tNV_SEQ_trkDesStatus_all     0xffffffff
#define m_tNV_SEQ_trkDesStatus_words_trkDesStatusL     0xffff
#define m_tNV_SEQ_trkDesStatus_words_trkDesStatusH     0xffff
#define m_tNV_SEQ_desFifoWrData_all     0xffffffff
#define m_tNV_SEQ_desFifoWrData_words_desFifoWrDataL     0xffff
#define m_tNV_SEQ_desFifoWrData_words_desFifoWrDataH     0xffff
#define m_tNV_SEQ_desFifoRdData_all     0xffffffff
#define m_tNV_SEQ_desFifoRdData_words_desFifoRdDataL     0xffff
#define m_tNV_SEQ_desFifoRdData_words_desFifoRdDataH     0xffff
#define m_tNV_SEQ_desFifoWrPtr_all     0xffff
#define m_tNV_SEQ_desFifoWrPtr_bits_desWrPtr     0x7ff
#define m_tNV_SEQ_desFifoWrPtr_bits_rsvd     0xf800
#define m_tNV_SEQ_desFifoRdPtr_all     0xffff
#define m_tNV_SEQ_desFifoRdPtr_bits_desRdPtr     0x7ff
#define m_tNV_SEQ_desFifoRdPtr_bits_rsvd     0xf800
#define m_tNV_SEQ_desFifoExePtr_all     0xffff
#define m_tNV_SEQ_desFifoExePtr_bits_desExePtr     0x7ff
#define m_tNV_SEQ_desFifoExePtr_bits_rsvd     0xf800
#define m_tNV_SEQ_rsvd4     0xffff
#define m_tNV_SEQ_desLoopCnt     0xffff
#define m_tNV_SEQ_desLoopCntAdj     0xffff
#define m_tNV_SEQ_desFifoCnt_all     0xffff
#define m_tNV_SEQ_desFifoCnt_bits_desFifoCnt     0x3ff
#define m_tNV_SEQ_desFifoCnt_bits_rsvd     0xfc00
#define m_tNV_SEQ_desFifoRemain_all     0xffff
#define m_tNV_SEQ_desFifoRemain_bits_desFifoRem     0xfff
#define m_tNV_SEQ_desFifoRemain_bits_rsvd     0xf000
#define m_tNV_SEQ_auxFifoWrData_all     0xffffffff
#define m_tNV_SEQ_auxFifoWrData_words_auxFifoWrDataL     0xffff
#define m_tNV_SEQ_auxFifoWrData_words_auxFifoWrDataH     0xffff
#define m_tNV_SEQ_auxFifoRdData_all     0xffffffff
#define m_tNV_SEQ_auxFifoRdData_words_auxFifoRdDataL     0xffff
#define m_tNV_SEQ_auxFifoRdData_words_auxFifoRdDataH     0xffff
#define m_tNV_SEQ_auxFifoWrPtr_all     0xffff
#define m_tNV_SEQ_auxFifoWrPtr_bits_auxWrPtr     0xfff
#define m_tNV_SEQ_auxFifoWrPtr_bits_rsvd     0xf000
#define m_tNV_SEQ_auxFifoRdPtr_all     0xffff
#define m_tNV_SEQ_auxFifoRdPtr_bits_auxRdPtr     0xfff
#define m_tNV_SEQ_auxFifoRdPtr_bits_rsvd     0xf000
#define m_tNV_SEQ_auxFifoPopPtr_all     0xffff
#define m_tNV_SEQ_auxFifoPopPtr_bits_auxPopPtr     0xfff
#define m_tNV_SEQ_auxFifoPopPtr_bits_rsvd     0xf000
#define m_tNV_SEQ_rsvd6     0xffff
#define m_tNV_SEQ_auxFifoPopCnt_all     0xffff
#define m_tNV_SEQ_auxFifoPopCnt_bits_auxPopCnt     0xfff
#define m_tNV_SEQ_auxFifoPopCnt_bits_rsvd     0xf000
#define m_tNV_SEQ_auEncDoneCnt     0xffff
#define m_tNV_SEQ_auDecDoneCnt     0xffff
#define m_tNV_SEQ_auEncRcvCnt     0xffff
#define m_tNV_SEQ_auDecRcvCnt     0xffff
#define m_tNV_SEQ_rowInc_all     0xffffffff
#define m_tNV_SEQ_rowInc_words_rowIncL     0xffff
#define m_tNV_SEQ_rowInc_words_rowIncH     0xffff
#define m_tNV_SEQ_cfDesXferCntSel0     0xffff
#define m_tNV_SEQ_cfDesXferCntSel1     0xffff
#define m_tNV_SEQ_cfDesColAddrSel0     0xffff
#define m_tNV_SEQ_cfDesColAddrSel1     0xffff
#define m_tNV_SEQ_afDesXferCntSel0     0xffff
#define m_tNV_SEQ_afDesXferCntSel1     0xffff
#define m_tNV_SEQ_afDesColAddrSel0     0xffff
#define m_tNV_SEQ_afDesColAddrSel1     0xffff
#define m_tNV_SEQ_afDesRowAddrSel0_all     0xffffffff
#define m_tNV_SEQ_afDesRowAddrSel0_words_afDesRowAdrSel0L     0xffff
#define m_tNV_SEQ_afDesRowAddrSel0_words_afDesRowAdrSel0H     0xffff
#define m_tNV_SEQ_afDesRowAddrSel1_all     0xffffffff
#define m_tNV_SEQ_afDesRowAddrSel1_words_afDesRowAdrSel1L     0xffff
#define m_tNV_SEQ_afDesRowAddrSel1_words_afDesRowAdrSel1H     0xffff

//---------------
#define m_tNV_SEQ_TIMING_CONFIG_all     0xffff
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev0     0x1
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev1     0x2
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev2     0x4
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev3     0x8
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev4     0x10
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev5     0x20
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev6     0x40
#define m_tNV_SEQ_TIMING_CONFIG_bits_dev7     0x80
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt0     0x100
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt1     0x200
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt2     0x400
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt3     0x800
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt4     0x1000
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt5     0x2000
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt6     0x4000
#define m_tNV_SEQ_TIMING_CONFIG_bits_lt7     0x8000

//---------------
#define m_tNV_SEQ_LUN_CONFIG_all     0xffff
#define m_tNV_SEQ_LUN_CONFIG_bits_lunCh0     0xf
#define m_tNV_SEQ_LUN_CONFIG_bits_lunCh1     0xf0
#define m_tNV_SEQ_LUN_CONFIG_bits_lunCh2     0xf00
#define m_tNV_SEQ_LUN_CONFIG_bits_lunCh3     0xf000

//---------------
#define m_tNV_FC_flashIntfConfig_all     0xffff
#define m_tNV_FC_flashIntfConfig_bits_flashmode     0x3
#define m_tNV_FC_flashIntfConfig_bits_flashType     0xc
#define m_tNV_FC_flashIntfConfig_bits_flashBW     0x30
#define m_tNV_FC_flashIntfConfig_bits_intf_reset     0x40
#define m_tNV_FC_flashIntfConfig_bits_pd_en     0x80
#define m_tNV_FC_flashIntfConfig_bits_nfif     0x100
#define m_tNV_FC_flashIntfConfig_bits_clkPdEn     0x200
#define m_tNV_FC_flashIntfConfig_bits_extRowEn     0x400
#define m_tNV_FC_flashIntfConfig_bits_eceEn     0x800
#define m_tNV_FC_flashIntfConfig_bits_clkStopEn     0x1000
#define m_tNV_FC_flashIntfConfig_bits_tsbMode     0x2000
#define m_tNV_FC_flashIntfConfig_bits_fifteenCeEn     0x4000
#define m_tNV_FC_flashIntfConfig_bits_rsvd     0x8000
#define m_tNV_FC_dirIndirConfig_all     0xffff
#define m_tNV_FC_dirIndirConfig_bits_dev_num     0xff
#define m_tNV_FC_dirIndirConfig_bits_chan_num     0xf00
#define m_tNV_FC_dirIndirConfig_bits_en_aw     0x1000
#define m_tNV_FC_dirIndirConfig_bits_lt_latchTiming     0x2000
#define m_tNV_FC_dirIndirConfig_bits_rsvd     0xc000
#define m_tNV_FC_intfTimingCtrl1_all     0xffff
#define m_tNV_FC_intfTimingCtrl1_bits_T1     0x7
#define m_tNV_FC_intfTimingCtrl1_bits_T2     0x38
#define m_tNV_FC_intfTimingCtrl1_bits_T3     0x1c0
#define m_tNV_FC_intfTimingCtrl1_bits_T4     0xe00
#define m_tNV_FC_intfTimingCtrl1_bits_T5     0x3000
#define m_tNV_FC_intfTimingCtrl1_bits_T6     0xc000
#define m_tNV_FC_intfTimingCtrl2_all     0xffff
#define m_tNV_FC_intfTimingCtrl2_bits_T1     0x7
#define m_tNV_FC_intfTimingCtrl2_bits_T2     0x38
#define m_tNV_FC_intfTimingCtrl2_bits_T3     0x1c0
#define m_tNV_FC_intfTimingCtrl2_bits_T4     0xe00
#define m_tNV_FC_intfTimingCtrl2_bits_T5     0x3000
#define m_tNV_FC_intfTimingCtrl2_bits_T6     0xc000
#define m_tNV_FC_intfTimingCtrl3_all     0xffff
#define m_tNV_FC_intfTimingCtrl3_bits_T1     0x7
#define m_tNV_FC_intfTimingCtrl3_bits_T2     0x38
#define m_tNV_FC_intfTimingCtrl3_bits_T3     0x1c0
#define m_tNV_FC_intfTimingCtrl3_bits_T4     0xe00
#define m_tNV_FC_intfTimingCtrl3_bits_T5     0x3000
#define m_tNV_FC_intfTimingCtrl3_bits_T6     0xc000
#define m_tNV_FC_intfTimingCtrl4_all     0xffff
#define m_tNV_FC_intfTimingCtrl4_bits_T1     0x7
#define m_tNV_FC_intfTimingCtrl4_bits_T2     0x38
#define m_tNV_FC_intfTimingCtrl4_bits_T3     0x1c0
#define m_tNV_FC_intfTimingCtrl4_bits_T4     0xe00
#define m_tNV_FC_intfTimingCtrl4_bits_T5     0xf000
#define m_tNV_FC_dirAcesCtrlPort1_all     0xffff
#define m_tNV_FC_dirAcesCtrlPort1_bits_CLE     0x1
#define m_tNV_FC_dirAcesCtrlPort1_bits_ALE     0x2
#define m_tNV_FC_dirAcesCtrlPort1_bits_RE     0x4
#define m_tNV_FC_dirAcesCtrlPort1_bits_WE     0x8
#define m_tNV_FC_dirAcesCtrlPort1_bits_WP     0x10
#define m_tNV_FC_dirAcesCtrlPort1_bits_rsvd0     0x20
#define m_tNV_FC_dirAcesCtrlPort1_bits_CE     0x40
#define m_tNV_FC_dirAcesCtrlPort1_bits_OE_EN     0x80
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_CLE     0x100
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_ALE     0x200
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_RE     0x400
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_WE     0x800
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_WP     0x1000
#define m_tNV_FC_dirAcesCtrlPort1_bits_rsvd1     0x2000
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_CE     0x4000
#define m_tNV_FC_dirAcesCtrlPort1_bits_MON_RDYB     0x8000
#define m_tNV_FC_dirAcesAddrData     0xffff
#define m_tNV_FC_intfTimingCtrlCh0Ch1_all     0xffff
#define m_tNV_FC_intfTimingCtrlCh0Ch1_bits_T7Ch0     0x3f
#define m_tNV_FC_intfTimingCtrlCh0Ch1_bits_rsvd0     0xc0
#define m_tNV_FC_intfTimingCtrlCh0Ch1_bits_T7Ch1     0x3f00
#define m_tNV_FC_intfTimingCtrlCh0Ch1_bits_rsvd1     0xc000
#define m_tNV_FC_intfTimingCtrlCh2Ch3_all     0xffff
#define m_tNV_FC_intfTimingCtrlCh2Ch3_bits_T7Ch2     0x3f
#define m_tNV_FC_intfTimingCtrlCh2Ch3_bits_rsvd0     0xc0
#define m_tNV_FC_intfTimingCtrlCh2Ch3_bits_T7Ch3     0x3f00
#define m_tNV_FC_intfTimingCtrlCh2Ch3_bits_rsvd1     0xc000
#define m_tNV_FC_intfTimingCtrlCh4Ch5_all     0xffff
#define m_tNV_FC_intfTimingCtrlCh4Ch5_bits_T7Ch4     0x3f
#define m_tNV_FC_intfTimingCtrlCh4Ch5_bits_rsvd0     0xc0
#define m_tNV_FC_intfTimingCtrlCh4Ch5_bits_T7Ch5     0x3f00
#define m_tNV_FC_intfTimingCtrlCh4Ch5_bits_rsvd1     0xc000
#define m_tNV_FC_intfTimingCtrlCh6Ch7_all     0xffff
#define m_tNV_FC_intfTimingCtrlCh6Ch7_bits_T7Ch6     0x3f
#define m_tNV_FC_intfTimingCtrlCh6Ch7_bits_rsvd0     0xc0
#define m_tNV_FC_intfTimingCtrlCh6Ch7_bits_T7Ch7     0x3f00
#define m_tNV_FC_intfTimingCtrlCh6Ch7_bits_rsvd1     0xc000
#define m_tNV_FC_intfTimingCtrlCh8Ch9_all     0xffff
#define m_tNV_FC_intfTimingCtrlCh8Ch9_bits_T7Ch8     0x3f
#define m_tNV_FC_intfTimingCtrlCh8Ch9_bits_rsvd0     0xc0
#define m_tNV_FC_intfTimingCtrlCh8Ch9_bits_T7Ch9     0x3f00
#define m_tNV_FC_intfTimingCtrlCh8Ch9_bits_rsvd1     0xc000
#define m_tNV_FC_indirAcesConfig_all     0xffff
#define m_tNV_FC_indirAcesConfig_bits_command     0xf
#define m_tNV_FC_indirAcesConfig_bits_in_out     0x10
#define m_tNV_FC_indirAcesConfig_bits_ct     0x20
#define m_tNV_FC_indirAcesConfig_bits_fifo_reset     0x40
#define m_tNV_FC_indirAcesConfig_bits_start     0x80
#define m_tNV_FC_indirAcesConfig_bits_dummy_RBB     0x100
#define m_tNV_FC_indirAcesConfig_bits_dummy_CE     0x200
#define m_tNV_FC_indirAcesConfig_bits_rsvd     0x3c00
#define m_tNV_FC_indirAcesConfig_bits_fifo_status     0x4000
#define m_tNV_FC_indirAcesConfig_bits_rsvd0     0x8000
#define m_tNV_FC_indirAcesCmdPort1_all     0xffff
#define m_tNV_FC_indirAcesCmdPort1_bits_byte0     0xff
#define m_tNV_FC_indirAcesCmdPort1_bits_byte1     0xff00
#define m_tNV_FC_indirAcesCmdPort2_all     0xffff
#define m_tNV_FC_indirAcesCmdPort2_bits_byte2     0xff
#define m_tNV_FC_indirAcesCmdPort2_bits_byte3     0xff00
#define m_tNV_FC_indirAcesCmdPort3_all     0xffff
#define m_tNV_FC_indirAcesCmdPort3_bits_byte4     0xff
#define m_tNV_FC_indirAcesCmdPort3_bits_byte5     0xff00
#define m_tNV_FC_indirAcesCmdPort4_all     0xffff
#define m_tNV_FC_indirAcesCmdPort4_bits_byte6     0xff
#define m_tNV_FC_indirAcesCmdPort4_bits_byte7     0xff00
#define m_tNV_FC_indirAcesDataXferCnt     0xffff
#define m_tNV_FC_seqIntrStatus     0xffff
#define m_tNV_FC_seqErrorDesId     0xffff
#define m_tNV_FC_seqCtrl2_all     0xffff
#define m_tNV_FC_seqCtrl2_bits_seq_en     0x1
#define m_tNV_FC_seqCtrl2_bits_seq_reset     0x2
#define m_tNV_FC_seqCtrl2_bits_fail_bit     0x1c
#define m_tNV_FC_seqCtrl2_bits_ready_bit     0xe0
#define m_tNV_FC_seqCtrl2_bits_ch_sel     0xf00
#define m_tNV_FC_seqCtrl2_bits_str_sel     0x3000
#define m_tNV_FC_seqCtrl2_bits_strb_ctrl     0xc000
#define m_tNV_FC_seqCtrl1_all     0xffff
#define m_tNV_FC_seqCtrl1_bits_seq_en     0x1
#define m_tNV_FC_seqCtrl1_bits_seq_reset     0x2
#define m_tNV_FC_seqCtrl1_bits_fail_bit     0x1c
#define m_tNV_FC_seqCtrl1_bits_ready_bit     0xe0
#define m_tNV_FC_seqCtrl1_bits_ch_sel     0xf00
#define m_tNV_FC_seqCtrl1_bits_str_sel     0x3000
#define m_tNV_FC_seqCtrl1_bits_strb_ctrl     0xc000
#define m_tNV_FC_seqCmdPort1_all     0xffff
#define m_tNV_FC_seqCmdPort1_bits_rbyte0     0xff
#define m_tNV_FC_seqCmdPort1_bits_rbyte1     0xff00
#define m_tNV_FC_seqCmdPort2_all     0xffff
#define m_tNV_FC_seqCmdPort2_bits_rbyte2     0xff
#define m_tNV_FC_seqCmdPort2_bits_rbyte3     0xff00
#define m_tNV_FC_seqCmdPort3_all     0xffff
#define m_tNV_FC_seqCmdPort3_bits_pbyte0     0xff
#define m_tNV_FC_seqCmdPort3_bits_pbyte1     0xff00
#define m_tNV_FC_seqCmdPort4_all     0xffff
#define m_tNV_FC_seqCmdPort4_bits_ebyte0     0xff
#define m_tNV_FC_seqCmdPort4_bits_ebyte1     0xff00
#define m_tNV_FC_seqCmdPort5_all     0xffff
#define m_tNV_FC_seqCmdPort5_bits_sbyte     0xff
#define m_tNV_FC_seqCmdPort5_bits_abyte     0xff00
#define m_tNV_FC_seqCmdPort6_all     0xffff
#define m_tNV_FC_seqCmdPort6_bits_ssaByte     0xff
#define m_tNV_FC_seqCmdPort6_bits_rsvd     0xff00
#define m_tNV_FC_seqStatusPort_all     0xffff
#define m_tNV_FC_seqStatusPort_bits_flash_status     0xff
#define m_tNV_FC_seqStatusPort_bits_desc_id     0xff00
#define m_tNV_FC_seqTimingCtrl1_all     0xffff
#define m_tNV_FC_seqTimingCtrl1_bits_wcnt12     0x7f
#define m_tNV_FC_seqTimingCtrl1_bits_rsvd     0x80
#define m_tNV_FC_seqTimingCtrl1_bits_wcnt11     0x3f00
#define m_tNV_FC_seqTimingCtrl1_bits_div1     0xc000
#define m_tNV_FC_seqTimingCtrl2_all     0xffff
#define m_tNV_FC_seqTimingCtrl2_bits_wcnt22     0x7f
#define m_tNV_FC_seqTimingCtrl2_bits_rsvd     0x80
#define m_tNV_FC_seqTimingCtrl2_bits_wcnt21     0x3f00
#define m_tNV_FC_seqTimingCtrl2_bits_div2     0xc000
#define m_tNV_FC_seqTimingCtrl3_all     0xffff
#define m_tNV_FC_seqTimingCtrl3_bits_wcnt32     0x7f
#define m_tNV_FC_seqTimingCtrl3_bits_rsvd     0x80
#define m_tNV_FC_seqTimingCtrl3_bits_wcnt31     0x3f00
#define m_tNV_FC_seqTimingCtrl3_bits_div3     0xc000
#define m_tNV_FC_seqTimingCtrl4_all     0xffff
#define m_tNV_FC_seqTimingCtrl4_bits_wcnt42     0x7f
#define m_tNV_FC_seqTimingCtrl4_bits_rsvd     0x80
#define m_tNV_FC_seqTimingCtrl4_bits_wcnt41     0x3f00
#define m_tNV_FC_seqTimingCtrl4_bits_div4     0xc000
#define m_tNV_FC_seqTimingCtrl5_all     0xffff
#define m_tNV_FC_seqTimingCtrl5_bits_pcnt52     0x7f
#define m_tNV_FC_seqTimingCtrl5_bits_rsvd     0x80
#define m_tNV_FC_seqTimingCtrl5_bits_pcnt51     0xf00
#define m_tNV_FC_seqTimingCtrl5_bits_rsvd1     0x3000
#define m_tNV_FC_seqTimingCtrl5_bits_div5     0xc000
#define m_tNV_FC_seqTimingCtrl6_all     0xffff
#define m_tNV_FC_seqTimingCtrl6_bits_wcnt62     0x7f
#define m_tNV_FC_seqTimingCtrl6_bits_rsvd     0x80
#define m_tNV_FC_seqTimingCtrl6_bits_wcnt61     0x3f00
#define m_tNV_FC_seqTimingCtrl6_bits_div6     0xc000
#define m_tNV_FC_efFifoAcesConfig_all     0xffff
#define m_tNV_FC_efFifoAcesConfig_bits_efFifoSel     0xf
#define m_tNV_FC_efFifoAcesConfig_bits_efFifoAdrSel     0x10
#define m_tNV_FC_efFifoAcesConfig_bits_efFifoAcsEn     0x20
#define m_tNV_FC_efFifoAcesConfig_bits_rsvd     0x3c0
#define m_tNV_FC_efFifoAcesConfig_bits_testSel     0x3c00
#define m_tNV_FC_efFifoAcesConfig_bits_eDir     0x4000
#define m_tNV_FC_efFifoAcesConfig_bits_eDebug     0x8000
#define m_tNV_FC_efFifoAddrPort     0xffff
#define m_tNV_FC_efFifoDataPort1     0xffff
#define m_tNV_FC_efFifoDataPort2     0xffff
#define m_tNV_FC_efFifoTestPort_all     0xffff
#define m_tNV_FC_efFifoTestPort_bits_efSramRtc     0x3
#define m_tNV_FC_efFifoTestPort_bits_efSramWtc     0xc
#define m_tNV_FC_efFifoTestPort_bits_efSramRettst     0x10
#define m_tNV_FC_efFifoTestPort_bits_rsvd     0x20
#define m_tNV_FC_efFifoTestPort_bits_efBistFail     0x40
#define m_tNV_FC_efFifoTestPort_bits_efBistReady     0x80
#define m_tNV_FC_efFifoTestPort_bits_efFifoBistEn     0xff00

//---------------
#define m_tFCT_INT_all     0xffff
#define m_tFCT_INT_bits_aesIntr     0x1
#define m_tFCT_INT_bits_flashIntr     0x2
#define m_tFCT_INT_bits_seqIntr     0x4
#define m_tFCT_INT_bits_rsvd     0xfff8

//---------------

//---------------
#define m_tNV_ECU_ctrlConfig1_all     0xffff
#define m_tNV_ECU_ctrlConfig1_bits_ecSoftReset     0x1
#define m_tNV_ECU_ctrlConfig1_bits_rsvd     0xfffe
#define m_tNV_ECU_ctrlConfig2_all     0xffff
#define m_tNV_ECU_ctrlConfig2_bits_rsvd     0x1
#define m_tNV_ECU_ctrlConfig2_bits_sendOnUncorr     0x2
#define m_tNV_ECU_ctrlConfig2_bits_sendOnOvrlmt     0x4
#define m_tNV_ECU_ctrlConfig2_bits_sendOnMcrcErr     0x8
#define m_tNV_ECU_ctrlConfig2_bits_sendOnLbaMismatch     0x10
#define m_tNV_ECU_ctrlConfig2_bits_rsvd1     0x20
#define m_tNV_ECU_ctrlConfig2_bits_sendOnDppErr     0x40
#define m_tNV_ECU_ctrlConfig2_bits_rsvd2     0x80
#define m_tNV_ECU_ctrlConfig2_bits_stopOnHCrcErr     0x100
#define m_tNV_ECU_ctrlConfig2_bits_stopOnUncorr     0x200
#define m_tNV_ECU_ctrlConfig2_bits_stopOnOvrLmt     0x400
#define m_tNV_ECU_ctrlConfig2_bits_stopOnMCrcErr     0x800
#define m_tNV_ECU_ctrlConfig2_bits_stopOnLbaMismatch     0x1000
#define m_tNV_ECU_ctrlConfig2_bits_stopOnErase     0x2000
#define m_tNV_ECU_ctrlConfig2_bits_stopOnDppErr     0x4000
#define m_tNV_ECU_ctrlConfig2_bits_stopOn16Au     0x8000
#define m_tNV_ECU_ctrlConfig3_all     0xffff
#define m_tNV_ECU_ctrlConfig3_bits_rsvd     0x1
#define m_tNV_ECU_ctrlConfig3_bits_hostCrcEn     0x2
#define m_tNV_ECU_ctrlConfig3_bits_dataScrbEn     0x4
#define m_tNV_ECU_ctrlConfig3_bits_fit2PhyPage     0x8
#define m_tNV_ECU_ctrlConfig3_bits_longModeEn     0x10
#define m_tNV_ECU_ctrlConfig3_bits_erasePgDetEn     0x20
#define m_tNV_ECU_ctrlConfig3_bits_lbaRcvrMode     0x40
#define m_tNV_ECU_ctrlConfig3_bits_metaRdOnly     0x80
#define m_tNV_ECU_ctrlConfig3_bits_metaEccEn     0x100
#define m_tNV_ECU_ctrlConfig3_bits_bmPortConfig     0x200
#define m_tNV_ECU_ctrlConfig3_bits_sendStatusMode     0x400
#define m_tNV_ECU_ctrlConfig3_bits_hostLbaChkEn     0x800
#define m_tNV_ECU_ctrlConfig3_bits_hostLbaEn     0x1000
#define m_tNV_ECU_ctrlConfig3_bits_rsvd1     0xe000
#define m_tNV_ECU_ctrlConfig4_all     0xffff
#define m_tNV_ECU_ctrlConfig4_bits_longModeEccSize     0x3ff
#define m_tNV_ECU_ctrlConfig4_bits_rsvd     0xfc00
#define m_tNV_ECU_ctrlConfig5_all     0xffff
#define m_tNV_ECU_ctrlConfig5_bits_phyPageSize     0x3fff
#define m_tNV_ECU_ctrlConfig5_bits_rsvd     0xc000
#define m_tNV_ECU_ctrlConfig6_all     0xffff
#define m_tNV_ECU_ctrlConfig6_bits_eraseCntThrshd     0xff
#define m_tNV_ECU_ctrlConfig6_bits_rsvd     0xff00
#define m_tNV_ECU_ctrlConfig7_all     0xffff
#define m_tNV_ECU_ctrlConfig7_bits_metaSize     0xff
#define m_tNV_ECU_ctrlConfig7_bits_rsvd     0xff00
#define m_tNV_ECU_ctrlConfig8_all     0xffff
#define m_tNV_ECU_ctrlConfig8_bits_metaT     0xf
#define m_tNV_ECU_ctrlConfig8_bits_metaThrshd     0xf0
#define m_tNV_ECU_ctrlConfig8_bits_rsvd     0xff00
#define m_tNV_ECU_ctrlConfig11_all     0xffff
#define m_tNV_ECU_ctrlConfig11_bits_tWeak     0x7f
#define m_tNV_ECU_ctrlConfig11_bits_rsvd     0x80
#define m_tNV_ECU_ctrlConfig11_bits_tStrong     0x7f00
#define m_tNV_ECU_ctrlConfig11_bits_twoLevelEn     0x8000
#define m_tNV_ECU_ctrlConfig12_all     0xffff
#define m_tNV_ECU_ctrlConfig12_bits_thrshdWeak     0x7f
#define m_tNV_ECU_ctrlConfig12_bits_rsvd     0x80
#define m_tNV_ECU_ctrlConfig12_bits_thrshdStrong     0x7f00
#define m_tNV_ECU_ctrlConfig12_bits_rsvd1     0x8000
#define m_tNV_ECU_encodeStatus_all     0xffff
#define m_tNV_ECU_encodeStatus_bits_encResume     0x1
#define m_tNV_ECU_encodeStatus_bits_hostCrcErr     0x2
#define m_tNV_ECU_encodeStatus_bits_encDppErr     0x4
#define m_tNV_ECU_encodeStatus_bits_rsvd     0xfff8
#define m_tNV_ECU_decodeStatus1_all     0xffff
#define m_tNV_ECU_decodeStatus1_bits_decResume     0x1
#define m_tNV_ECU_decodeStatus1_bits_curAuUncorr     0x2
#define m_tNV_ECU_decodeStatus1_bits_curAuOvrlmt     0x4
#define m_tNV_ECU_decodeStatus1_bits_curAuMCrc1Err     0x8
#define m_tNV_ECU_decodeStatus1_bits_curAuMCrc2Err     0x10
#define m_tNV_ECU_decodeStatus1_bits_curAuLbaMismatch     0x20
#define m_tNV_ECU_decodeStatus1_bits_curAuErase     0x40
#define m_tNV_ECU_decodeStatus1_bits_curAuDppErr     0x80
#define m_tNV_ECU_decodeStatus1_bits_rsvd     0x100
#define m_tNV_ECU_decodeStatus1_bits_curAu16     0x200
#define m_tNV_ECU_decodeStatus1_bits_configErr1     0x400
#define m_tNV_ECU_decodeStatus1_bits_configErr2     0x800
#define m_tNV_ECU_decodeStatus1_bits_configErr3     0x1000
#define m_tNV_ECU_decodeStatus1_bits_configErr4     0x2000
#define m_tNV_ECU_decodeStatus1_bits_configErr5     0x4000
#define m_tNV_ECU_decodeStatus1_bits_rsvd1     0x8000
#define m_tNV_ECU_decodeStatus4_all     0xffff
#define m_tNV_ECU_decodeStatus4_bits_auCorrCnt     0x1ff
#define m_tNV_ECU_decodeStatus4_bits_rsvd     0xfe00
#define m_tNV_ECU_accumCorrCnt     0xffff
#define m_tNV_ECU_accumUncleanCnt     0xffff
#define m_tNV_ECU_accumUncorrAu     0xffff
#define m_tNV_ECU_accumOvrlmtAu     0xffff

//---------------
#define m_tNV_AES_aesCtrl_all     0xffff
#define m_tNV_AES_aesCtrl_bits_aesSoftReset     0x1
#define m_tNV_AES_aesCtrl_bits_rsvd0     0xe
#define m_tNV_AES_aesCtrl_bits_entropyEnable     0x10
#define m_tNV_AES_aesCtrl_bits_rsvd1     0xffe0
#define m_tNV_AES_aesStatus_all     0xffff
#define m_tNV_AES_aesStatus_bits_decryptErr     0x1
#define m_tNV_AES_aesStatus_bits_encryptErr     0x2
#define m_tNV_AES_aesStatus_bits_rsvd0     0xc
#define m_tNV_AES_aesStatus_bits_entropyRdy     0x10
#define m_tNV_AES_aesStatus_bits_rsvd1     0xe0
#define m_tNV_AES_aesStatus_bits_aesDisable     0x100
#define m_tNV_AES_aesStatus_bits_uartDisable     0x200
#define m_tNV_AES_aesStatus_bits_faDisable     0x400
#define m_tNV_AES_aesStatus_bits_rsvd2     0xf800
#define m_tNV_AES_aesRdWrReqNum_all     0xffff
#define m_tNV_AES_aesRdWrReqNum_bits_aesAccNum     0xf
#define m_tNV_AES_aesRdWrReqNum_bits_rsvd0     0xfff0
#define m_tNV_AES_aesAccessAuth_all     0xffff
#define m_tNV_AES_aesAccessAuth_bits_aesAccGrant     0xf
#define m_tNV_AES_aesAccessAuth_bits_aesAccRst     0x10
#define m_tNV_AES_aesAccessAuth_bits_rsvd0     0xffe0
#define m_tNV_AES_rsvd1     0xffff
#define m_tNV_AES_aesConfig_all     0xffff
#define m_tNV_AES_aesConfig_bits_aesMode     0x3
#define m_tNV_AES_aesConfig_bits_rsvd0     0x4
#define m_tNV_AES_aesConfig_bits_entropySrc     0x18
#define m_tNV_AES_aesConfig_bits_aesNkMode     0x20
#define m_tNV_AES_aesConfig_bits_rsvd1     0xc0
#define m_tNV_AES_aesConfig_bits_aesErrStop     0x100
#define m_tNV_AES_aesConfig_bits_cryptErrMsk     0x200
#define m_tNV_AES_aesConfig_bits_rsvd2     0xfc00
#define m_tNV_AES_entropyNum     0xffff
#define m_tNV_AES_encryptKeyL     0xffff
#define m_tNV_AES_encryptKeyH     0xffff
#define m_tNV_AES_decryptKeyL     0xffff
#define m_tNV_AES_decryptKeyH     0xffff
#define m_tNV_AES_encDecPtr_all     0xffff
#define m_tNV_AES_encDecPtr_bits_encKeyPtr     0x3
#define m_tNV_AES_encDecPtr_bits_rsvd0     0x7c
#define m_tNV_AES_encDecPtr_bits_encPtrInc     0x80
#define m_tNV_AES_encDecPtr_bits_decKeyPtr     0x300
#define m_tNV_AES_encDecPtr_bits_rsvd1     0x7c00
#define m_tNV_AES_encDecPtr_bits_decPtrInc     0x8000
#define m_tNV_AES_rsvd2     0xffff
#define m_tNV_AES_encryptionIv     0xffff
#define m_tNV_AES_rsvd3     0xffff
#define m_tNV_AES_decryptionIv     0xffff

// From mSFRS.h
#define m_tCPU_INTR_bits_watchdogTO     0x8000
#define m_tCPU_INTR_bits_comTx          0x4000
#define m_tCPU_INTR_bits_comRxLatched   0x2000
#define m_tCPU_INTR_bits_sataIn         0x0008
#define m_tCPU_INTR_bits_hdcInt         0x0002
#define m_tCPU_INTR_bits_servoInt       0x0001

#define m_mSOC_INTR_bits_itcmRMW        0x8000
#define m_mSOC_INTR_bits_timer4         0x1000
#define m_mSOC_INTR_bits_timer3         0x0800
#define m_mSOC_INTR_bits_timer2         0x0400
#define m_mSOC_INTR_bits_timer1         0x0200
#define m_mSOC_INTR_bits_timer0         0x0100
#define m_mSOC_INTR_bits_test16         0x0080
#define m_mSOC_INTR_bits_enSpinErr      0x0040
#define m_mSOC_INTR_bits_minnowSpinInt  0x0020
#define m_mSOC_INTR_bits_uartTx         0x0008
#define m_mSOC_INTR_bits_uartRx         0x0004
#define m_mSOC_INTR_bits_IPCStatusRead  0x0002
#define m_mSOC_INTR_bits_IPCCmdWritten  0x0001
#define m_mSOC_INTR_bits_all            0xFFFF

#define m_mTESTIO_bits_b15		0x8000
#define m_mTESTIO_bits_b14		0x4000
#define m_mTESTIO_bits_b13		0x2000
#define m_mTESTIO_bits_b12		0x1000
#define m_mTESTIO_bits_b11		0x0800
#define m_mTESTIO_bits_b10		0x0400
#define m_mTESTIO_bits_b9		0x0200
#define m_mTESTIO_bits_b8		0x0100
#define m_mTESTIO_bits_b7		0x0080
#define m_mTESTIO_bits_b6		0x0040
#define m_mTESTIO_bits_b5		0x0020
#define m_mTESTIO_bits_b4		0x0010
#define m_mTESTIO_bits_b3		0x0008
#define m_mTESTIO_bits_b2		0x0004
#define m_mTESTIO_bits_b1		0x0002
#define m_mTESTIO_bits_b0		0x0001
#define m_mTESTIO_all		0xFFFF

#define m_tDOH_SFRS_cpuConfig_bits_rsvd7		0xFF80
#define m_tDOH_SFRS_cpuConfig_bits_lcBistEn		0x0040
#define m_tDOH_SFRS_cpuConfig_bits_lcBistFail		0x0020
#define m_tDOH_SFRS_cpuConfig_bits_lcBistRdy		0x0010
#define m_tDOH_SFRS_cpuConfig_bits_lcFlushDis		0x0008
#define m_tDOH_SFRS_cpuConfig_bits_lcInvalid		0x0004
#define m_tDOH_SFRS_cpuConfig_bits_rsvd0		0x0003
#define m_tDOH_SFRS_cpuConfig_all		0xFFFF

#define m_tDOH_SFRS_configData_bits_rsvd12		0xF000
#define m_tDOH_SFRS_configData_bits_cselIn		0x0800
#define m_tDOH_SFRS_configData_bits_csIn		0x0400
#define m_tDOH_SFRS_configData_bits_masIn		0x0200
#define m_tDOH_SFRS_configData_bits_slvIn		0x0100
#define m_tDOH_SFRS_configData_bits_rsvd3		0x00F8
#define m_tDOH_SFRS_configData_bits_csOut		0x0004
#define m_tDOH_SFRS_configData_bits_masOut		0x0002
#define m_tDOH_SFRS_configData_bits_slvOut		0x0001
#define m_tDOH_SFRS_configData_all		0xFFFF

#define m_tDOH_SFRS_configLatched_bits_rsvd		0xF000
#define m_tDOH_SFRS_configLatched_bits_csel		0x0800
#define m_tDOH_SFRS_configLatched_bits_cs		0x0400
#define m_tDOH_SFRS_configLatched_bits_master		0x0200
#define m_tDOH_SFRS_configLatched_bits_slave		0x0100
#define m_tDOH_SFRS_configLatched_bits_rsvd4		0x00F8
#define m_tDOH_SFRS_configLatched_bits_bootStap		0x0007
#define m_tDOH_SFRS_configLatched_all		0xFFFF

#define m_tDOH_SFRS_ioControl_bits_rsvd11		0xF000
#define m_tDOH_SFRS_ioControl_bits_csPol		0x0800
#define m_tDOH_SFRS_ioControl_bits_csDir		0x0400
#define m_tDOH_SFRS_ioControl_bits_masDir		0x0200
#define m_tDOH_SFRS_ioControl_bits_slvDir		0x0100
#define m_tDOH_SFRS_ioControl_bits_rsvd4		0x00F0
#define m_tDOH_SFRS_ioControl_bits_test15dir		0x0008
#define m_tDOH_SFRS_ioControl_bits_test14dir		0x0004
#define m_tDOH_SFRS_ioControl_bits_test13dir		0x0002
#define m_tDOH_SFRS_ioControl_bits_test12dir		0x0001
#define m_tDOH_SFRS_ioControl_all		0xFFFF

#define m_tDOH_SFRS_intrControl_bits_rsvd11		0xF800
#define m_tDOH_SFRS_intrControl_bits_irqSel		0x0700
#define m_tDOH_SFRS_intrControl_bits_rsvd7		0x0080
#define m_tDOH_SFRS_intrControl_bits_fiqSel		0x0070
#define m_tDOH_SFRS_intrControl_bits_rsvd2		0x000C
#define m_tDOH_SFRS_intrControl_bits_swIrq		0x0002
#define m_tDOH_SFRS_intrControl_bits_swFiq		0x0001
#define m_tDOH_SFRS_intrControl_all		0xFFFF

// From mUART.h
#define m_tUART_RCV_BUFFER_bits_breakDetected		0x8000
#define m_tUART_RCV_BUFFER_bits_framingErr		0x4000
#define m_tUART_RCV_BUFFER_bits_parityErr		0x2000
#define m_tUART_RCV_BUFFER_bits_overRunErr		0x1000
#define m_tUART_RCV_BUFFER_bits_rsvd		0x0F00
#define m_tUART_RCV_BUFFER_bits_data		0x00FF
#define m_tUART_RCV_BUFFER_all		0xFFFF

#define m_tUART_XMIT_HOLD_bits_rsvd		0xFF00
#define m_tUART_XMIT_HOLD_bits_data		0x00FF
#define m_tUART_XMIT_HOLD_all		0xFFFF

#define m_tUART_CNTRL_bits_rsvd1		0xE000
#define m_tUART_CNTRL_bits_statusMirrorEn		0x1000
#define m_tUART_CNTRL_bits_loopAckModeEn		0x0800
#define m_tUART_CNTRL_bits_sendBrkSequ		0x0400
#define m_tUART_CNTRL_bits_prtyEnable		0x0200
#define m_tUART_CNTRL_bits_twoStopBits		0x0100
#define m_tUART_CNTRL_bits_rsvd0		0x0080
#define m_tUART_CNTRL_bits_xmitEmptyIntEn		0x0040
#define m_tUART_CNTRL_bits_xmitRdyIntEn		0x0020
#define m_tUART_CNTRL_bits_rcvRdyIntEn		0x0010
#define m_tUART_CNTRL_bits_breakDetIntEn		0x0008
#define m_tUART_CNTRL_bits_frameErrIntEn		0x0004
#define m_tUART_CNTRL_bits_prtyErrIntEn		0x0002
#define m_tUART_CNTRL_bits_overRunIntEn		0x0001
#define m_tUART_CNTRL_all		0xFFFF

#define m_tUART_STATUS_bits_rsvd		0xFF80
#define m_tUART_STATUS_bits_xmitEmpty		0x0040
#define m_tUART_STATUS_bits_xmitRdy		0x0020
#define m_tUART_STATUS_bits_xcevRdy		0x0010
#define m_tUART_STATUS_bits_breakDetected		0x0008
#define m_tUART_STATUS_bits_frameErrr		0x0004
#define m_tUART_STATUS_bits_parityErr		0x0002
#define m_tUART_STATUS_bits_overRunEr		0x0001
#define m_tUART_STATUS_all		0xFFFF

#define m_tUART_BAUD_DIVISOR_bits_rsvd		0xFC00
#define m_tUART_BAUD_DIVISOR_bits_divisor		0x03FF
#define m_tUART_BAUD_DIVISOR_all		0xFFFF

#endif // _m9187SYM_H_INC
